### ISSUE TITLE
automatically updating documentation?

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#116]
It doesn't look like all the new docstrings have been added to the documentation. 

e.g.
https://github.com/YosefLab/scVI/blob/adcb5035bd9884f0c52675f484c6465e69da3523/scvi/inference/classifier_inference.py#L9-L19

doesn't show up in
https://scvi.readthedocs.io/en//latest/models.html#module-scvi.models

Is there a way to make it so that readthedocs automatically stay in sync with the master branch?

**Comment by imyiningliu** [comment]
Readthedocs is sync with the master branch right now, but I think we need to put the `.rst` files on will class we want to include on readthedocs. I will update the new docstrings tonight.

**Comment by jeff-regier** [comment]
Doesn't look like it updated

**Comment by imyiningliu** [comment]
sorry, the build was failing but it should be resolved by #120

**Comment by imyiningliu** [comment]
It's updated now. I think I still need to trigger the `build` on `readthedocs`.

**Comment by imyiningliu** [comment]
The titles under usage section are very long. Should I shorten the titles on jupyter notebook so that it can look better? 

(Also the inference section doesn't show up - looking into that. )

**Comment by jeff-regier** [comment]
Yes, short titles are good.

Is there a way to have trigger the readthedocs build automatically, perhaps by adding something to . travis.yml?

**Comment by jeff-regier** [comment]
Hmm... a lot of the titles in the notebook really would be better as text, or perhaps bold text. Let me commit a revised version.

**Comment by jeff-regier** [comment]
I still don't see any documentation for, e.g., classifier inference:

https://scvi.readthedocs.io/en/master/inference.html

**Comment by jeff-regier** [comment]
Fixed by #130 and adding a webhook.
