### ISSUE TITLE
notebook of figures from the original scVI paper

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#123]
Let's add a Jupyter notebook to the `doc/examples` directory that shows how to generate the figures (and one table) from the original scVI paper. It isn't necessary to reconstruct the parts of the figures and the table about competing methods that we compare to---we just need the parts about scVI.

- [x] Figure 1c. runtime; BRAIN_LARGE
- [x] Table 1. log likelihood; BRAIN_LARGE
- [x] Figure 2. imputation; CORTEX
- [ ] Figure 3. interpreting latent space; tsne plot and heatmap; CORTEX, HEMATO, random zinb
- [x] Figure 4. batch effect removal; tsne plot; RETINA
- [ ] Figure 5. differential expression; plots; PBMC
- [ ] Figure 6. plots; PBMC 
- [ ] Figure 7. posterior plots; CORTEX
- [ ] Figure 8. silhouette and batch mixing entropy; PBMC, CORTEX, CBMC, RETINA
- [x] Figure 9. imputation; CORTEX
- [x] Figure 10. imputation; CORTEX
- [x] Figure 11. imputation; CORTEX and BRAIN_LARGE
- [ ] Figure 12. DE; plots; PBMC
- [ ] Figure 13. DE; plots; BRAIN_SMALL
- [x] Figure 14. imputation; BRAIN_LARGE, CORTEX
- [ ] Figure 15. clustering; random and HEMATO
- [x] Figure 16. tsne; HEMATO

**Comment by imyiningliu** [comment]
Do you remember how many epochs you used for the runtime figure (figure 1)? I only found the runtime code for other softwares on `reproducibility` notebook > <

**Comment by jeff-regier** [comment]
^ @romain-lopez

**Comment by romain-lopez** [comment]
Hi Yining, 

For this updated figure, let us use max_epochs = 125 but with early stopping (it should stop way before 125 epochs).

Romain
