### ISSUE TITLE
refactoring: metric -> inference

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#155]
We have a bunch of methods in our inference classes that do nothing but call a function in the `metric` directory. e.g.,

https://github.com/YosefLab/scVI/blob/e1c210135351e434aa619e72cdcf3dab04d35c3d/scvi/inference/variational_inference.py#L71-L75

It'd be clearer to just have the code the implements the method in the method -- better for reading the code not to have to jump to a different file in a different directory.

I'd be glad to get rid of the `metric` directory entirely, if possible.

**Comment by Edouard360** [comment]
In https://github.com/YosefLab/scVI/tree/delete_metrics, I have move most methods as you said and deleted the `metrics` folder.

I just move `log_likelihood.py` into models rather that variational inference, since it is used by the models. Is that ok ?

**Comment by jeff-regier** [comment]
Great! Yes, putting log likelihood there makes sense
