### ISSUE TITLE
refactoring: SemiSupervisedVariationalInference -> classifier_inference.py

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#157]
It might be nice to move `SemiSupervisedVariationalInference` and all it's subclasses to `classifier_inference.py`, so that the annotation inference code is all together. Then we could also put the code from `metrics/classification.py` into `inference/classifier_inference.py` too, above and outside of all the classes in that file for all to use.

**Comment by Edouard360** [comment]
I did the branch `delete_metrics` for that - https://github.com/YosefLab/scVI/tree/delete_metrics
