### ISSUE TITLE
RETINA data set

### ISSUE THREAD

**Issue by pedrofale** [YosefLab/scVI#169]
In the paper the RETINA data set has 27,499 cells. If I call RetinaDataset(), however, I only get 19,829 cells. What processing did you do? Also, it would be handy if it came with cell type names instead of just number ids.

**Comment by Edouard360** [comment]
To complete answer above I can already provide the correspondence:

```
label = ["RBC","MG","BC5A","BC7","BC6","BC5C","BC1A","BC3B","BC1B","BC2","BC5D","BC3A","BC5B","BC4","BC8_9"]
```

**Comment by pedrofale** [comment]
Cool, thanks for clearing that up!
