### ISSUE TITLE
docstrings for vae_fish.py

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#171]
We're missing docstrings current for the methods in `vae_fish.py`.

- [ ] get_latents
- [ ] sample_from_posterior_z
- [ ] sample_from_posterior_l
- [ ] get_sample_scale
- [ ] get_sample_rate
- [ ] get_sample_rate_fish
- [ ] classify
- [ ] forward

We'd like to have docstrings that look more like this one:
https://github.com/YosefLab/scVI/blob/8147cb6b11717adb7578cf95c97c8ef5ae3c3386/scvi/models/modules.py#L42-L50

**Comment by jules-samaran** [comment]
commit 18a3c7ec2e318ffb284f5641cf4c3218cbc3b05e
