### ISSUE TITLE
organize inference code by project

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#174]
Within the inference directory, it'd better to have all the smFISH-specific code together in one file `fish.py` perhaps), and all the annotation-specific code together in `annotation.py`. Organizing our inference directory by project will let us keep reusing the same codebase for many projects, without each project making the codebase more complicated.

The first thing to do is to make two new subclasses of `Posterior`: `FishPosterior` to `fish.py` and `AnnotationPosterior` to `annotation.py`. Then move the fish-specific methods from `Posterior` to `FishPosterior` and the annotation-specific methods to `AnnotationPosterior`. E.g., the method Posterior.fish_ll()` becomes `FishPosterior.ll()`.

The file `fish.py` would also contain `FishTrainer` (currently in `inference.py`) as well as everything that is now in `experimental_inference.py`.

**Comment by jeff-regier** [comment]
@jules-samaran This issue would get you familiar with the code organization---good to work on it while Eddie is around.

**Comment by jeff-regier** [comment]
@jules-samaran It looks like your making changes to address this issue on a branch. Will you open up a pull request for it?

**Comment by jules-samaran** [comment]
I thought that @Edouard360  had included these changes in a pull request on Friday, I haven't ever made any pull request so I will ask him about that and open up a pull request if all the changes I've made since I arrived weren't included in any pull request

**Comment by jeff-regier** [comment]
Ah, I see. Yes, it looks like your changes were included in that PR.
