### ISSUE TITLE
Extracting data from the model

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scVI#188]
We have some requests on how to extract the following information as np.array type from the model such as:
+ A latent space for a given set of cells
+ Imputed values on a given set of cells

It is important to update our introductory notebook to reflect those new features. The latent space is what our users would like to see at first sight.

**Comment by romain-lopez** [comment]
Also, a function giving the imputed values given the latent space and the batch would be very important for @chenlingantelope  analysis.

**Comment by mchamber-boston** [comment]
It would certainly be useful to have an scvi wrapper that saves the imputed values for the entire expression matrix (gene by cell) in standard formats (e.g., mtx or csv), since my group is currently studying different imputation methods.
