### ISSUE TITLE
Saving a trained model?

### ISSUE THREAD

**Issue by vals** [YosefLab/scVI#192]
Hi,

After training a large model on a large data set, it would be nice if I could save it so I could re-use it for e.g. future DE analysis, or maybe to warm-start with new data, or to send to collaborators.

Is there any way to save a model for future loading? Is using pickle the best way to go about this?

Best,
/Valentine

**Comment by vals** [comment]
Thanks! This is easy enough!

It didn't work directly as written here though, it seems you need to do 
```
...
torch.save(model.state_dict(), 'mytraining.pt')
```

**Comment by wikiselev** [comment]
I am now in 2022 and none of the above worked for me... Only this worked with `scvi-tools==0.17.1`:
```
model.save(path_to_model_folder)
```
To load the model:
```
model = scvi.model.SCVI.load(path_to_model_folder, adata)
```
where adata is AnnData object organized in the same way as data used to train model.

**Comment by adamgayoso** [comment]
Hi @wikiselev thanks for using scvi-tools. Just want to highlight this info is readily available in the documentation/tutorials, and that the code in this issue doesn't work because we added another layer on top of PyTorch Modules

**Comment by wikiselev** [comment]
Thanks @adamgayoso! Could you provide a link to the documentation where it is mentioned as I can't find it anywhere?

**Comment by adamgayoso** [comment]
1. https://docs.scvi-tools.org/en/stable/tutorials/notebooks/api_overview.html#Saving-and-loading
2. https://docs.scvi-tools.org/en/stable/api/reference/scvi.model.SCVI.html#save

**Comment by shashkat** [comment]
Hello there, I have followed the links above, but upon loading the data, I am getting an error. I don't know what is wrong. Any help would be highly appreciated.
The error:

INFO     No backup URL provided for missing file /content/ldvae/model.pt                                           
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/scvi/model/base/_utils.py](https://localhost:8080/#) in _load_saved_files(dir_path, load_adata, prefix, map_location, backup_url)
     68         _download(backup_url, dir_path, model_file_name)
---> 69         model = torch.load(model_path, map_location=map_location)
     70     except FileNotFoundError as exc:

5 frames
FileNotFoundError: [Errno 2] No such file or directory: '/content/ldvae/model.pt'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/scvi/model/base/_utils.py](https://localhost:8080/#) in _load_saved_files(dir_path, load_adata, prefix, map_location, backup_url)
     73             "If attempting to load a saved model from <v0.15.0, please use the util function "
     74             "`convert_legacy_save` to convert to an updated format."
---> 75         ) from exc
     76 
     77     model_state_dict = model["model_state_dict"]

ValueError: Failed to load model file at /content/ldvae/model.pt. If attempting to load a saved model from <v0.15.0, please use the util function `convert_legacy_save` to convert to an updated format.

**Comment by wikiselev** [comment]
Hi @shashkat , looks like you've used a wrong function for loading, try using `scvi.model.SCVI.load` instead of `scvi.model.LinearSCVI.load`.

**Comment by shashkat** [comment]
> 

Hi @wikiselev, thanks for the quick reply. I tried using `scvi.model.SCVI.load` instead of `scvi.model.LinearSCVI.load`, but am still getting the exact same error:

INFO     No backup URL provided for missing file /content/ldvae/model.pt                                           
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/scvi/model/base/_utils.py](https://localhost:8080/#) in _load_saved_files(dir_path, load_adata, prefix, map_location, backup_url)
     68         _download(backup_url, dir_path, model_file_name)
---> 69         model = torch.load(model_path, map_location=map_location)
     70     except FileNotFoundError as exc:

5 frames
FileNotFoundError: [Errno 2] No such file or directory: '/content/ldvae/model.pt'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/scvi/model/base/_utils.py](https://localhost:8080/#) in _load_saved_files(dir_path, load_adata, prefix, map_location, backup_url)
     73             "If attempting to load a saved model from <v0.15.0, please use the util function "
     74             "`convert_legacy_save` to convert to an updated format."
---> 75         ) from exc
     76 
     77     model_state_dict = model["model_state_dict"]

ValueError: Failed to load model file at /content/ldvae/model.pt. If attempting to load a saved model from <v0.15.0, please use the util function `convert_legacy_save` to convert to an updated format.

**Comment by adamgayoso** [comment]
It appears the names of the files have changed inside the ldvae directory, as well as some other folders like assets and variables that should not be there.

**Comment by vttrifonov** [comment]
The interface that has the training data as part of loading the model feels awkward to me. If feature names is all that is needed perhaps they can be included as part of the model metadata being saved and then read at load time. In fact I would like to be able to query this metadata after loading. I am running into this issue because I was handed an scvi saved pt file but do not have access to the training data (or the features used).   

`SCVI.prepare_query_anndata` is able to work only with a file name but load is not. This is strange: I should be able to load and then prepare. 

`prepare_query_anndata` also has an argument which lets you get the features: so this function returns either an index or an anndata object! This is also strange: how is returning an index preparing the anndata. I mean, you can use it to prepare afterwards but getting the index itself is not preparing.

**Comment by canergen** [comment]
Hi, it's a closed issue of two years ago and your request is somewhat confusing to me. If you want to get the feature names, you can read the saved model with torch.load and access all fields including the var_names. If you are trying to do something else, please open a new issue and give a clear description.

**Comment by vttrifonov** [comment]
Apologies for the confusing comment. My point is that the load interfaces are a bit confusing. For example, 

I tried `scvi.model.SCVI.load("model.pt")` but got `ValueError: Save path contains no saved anndata and no adata was passed`. On the other hand, `scvi.model.prepare_query_anndata(new_data, 'model.pt')` works and it does not complain about anything. It just seemed to me I should be able to do `load` and then `prepare_query_anndata` with loaded model.

The second comment was that `prepare_query_anndata` returns either an index or anndata which seemed to me a bit odd as a function interface. For example, If I want the features needed by the model perhaps a property that gives me that will be more appropriate than the prepare_query_anndata method with return_feature_vars=True which is not obvious at all as a way to get the required features. 

I admit these are a bit subjective and they are not blocking for me in any way (as you said there are ways to get things done) but thought I would share anyway.

**Comment by canergen** [comment]
Indeed we are currently looking into supporting loading models without AnnData. It's not as straightforward as the model classes were assumed to always contain a registered AnnData object. It is part of the roadmap for scVI-tools v1.3.
I assume we can deprecate the return_feature_vars option then (I wasn't aware of this feature and used torch.load).

**Comment by Eddie-Kngtlo** [comment]
Hi, I have came across a problem with loading a saved model. After training my model, I ran:
`scvi.model.SCVI.save(model, "path_to_model/")`
Then there is a model.pt file in the new directory. Then I tried loading my model:
`model_test = scvi.model.SCVI.load("model_untagged_3.17/", data)`
where data is the same data I used to train the model. (I just wanted to save the model to produce some repeatable results after changing parameters of the model)
This is the error message reported: 

---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
Cell In[97], line 1
----> 1 model_test = scvi.model.SCVI.load("model_untagged_3.17/", data)

File ~/(current directory)/.venv/lib/python3.9/site-packages/scvi/model/base/_base_model.py:681, in BaseModelClass.load(cls, dir_path, adata, accelerator, device, prefix, backup_url)
    668 load_adata = adata is None
    669 _, _, device = parse_device_args(
    670     accelerator=accelerator,
    671     devices=device,
    672     return_device="torch",
    673     validate_single_device=True,
    674 )
    676 (
    677     attr_dict,
    678     var_names,
    679     model_state_dict,
    680     new_adata,
--> 681 ) = _load_saved_files(
    682     dir_path,
    683     load_adata,
    684     map_location=device,
    685     prefix=prefix,
    686     backup_url=backup_url,
    687 )
    688 adata = new_adata if new_adata is not None else adata
    690 _validate_var_names(adata, var_names)

File ~/(current directory)/.venv/lib/python3.9/site-packages/scvi/model/base/_utils.py:66, in _load_saved_files(dir_path, load_adata, prefix, map_location, backup_url)
     64 try:
     65     _download(backup_url, dir_path, model_file_name)
---> 66     model = torch.load(model_path, map_location=map_location)
     67 except FileNotFoundError as exc:
     68     raise ValueError(
     69         f"Failed to load model file at {model_path}. "
     70         "If attempting to load a saved model from <v0.15.0, please use the util function "
     71         "`convert_legacy_save` to convert to an updated format."
     72     ) from exc

File ~/(current directory)/.venv/lib/python3.9/site-packages/torch/serialization.py:1470, in load(f, map_location, pickle_module, weights_only, mmap, **pickle_load_args)
   1462                 return _load(
   1463                     opened_zipfile,
   1464                     map_location,
   (...)
   1467                     **pickle_load_args,
   1468                 )
   1469             except pickle.UnpicklingError as e:
-> 1470                 raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
   1471         return _load(
   1472             opened_zipfile,
   1473             map_location,
   (...)
   1476             **pickle_load_args,
   1477         )
   1478 if mmap:

UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint. 
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL numpy.core.multiarray._reconstruct was not an allowed global by default. Please use `torch.serialization.add_safe_globals([_reconstruct])` or the `torch.serialization.safe_globals([_reconstruct])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
___________________________________________________________________________________________________________

I also tried using the methods based on pytorch mentioned in this page and it didn't seem to work. I also tried adding weights_only = True, and I got TypeError : load() got an unexpected keyword argument 'weights_only'

**Comment by LitalBarak96** [comment]
i also have the same problem,  am trying to 
scvi.model.SCVI.prepare_query_anndata(adata_BA, scvi_ref_path)

as you say in the manuel but get the same error

---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
Cell In[15], line 1
----> 1 scvi.model.SCVI.prepare_query_anndata(adata_BA, scvi_ref_path)

File ~/.local/lib/python3.9/site-packages/scvi/model/base/_archesmixin.py:190, in ArchesMixin.prepare_query_anndata(adata, reference_model, return_reference_var_names, inplace)
    159 @staticmethod
    160 def prepare_query_anndata(
    161     adata: AnnData,
   (...)
    164     inplace: bool = True,
    165 ) -> Optional[Union[AnnData, pd.Index]]:
    166     """Prepare data for query integration.
    167 
    168     This function will return a new AnnData object with padded zeros
   (...)
    188     in which case a pd.Index of reference var names is returned.
    189     """
--> 190     _, var_names, _ = _get_loaded_data(reference_model, device="cpu")
    191     var_names = pd.Index(var_names)
    193     if return_reference_var_names:

File ~/.local/lib/python3.9/site-packages/scvi/model/base/_archesmixin.py:323, in _get_loaded_data(reference_model, device)
    321 def _get_loaded_data(reference_model, device=None):
    322     if isinstance(reference_model, str):
--> 323         attr_dict, var_names, load_state_dict, _ = _load_saved_files(
    324             reference_model, load_adata=False, map_location=device
    325         )
    326     else:
    327         attr_dict = reference_model._get_user_attributes()

File ~/.local/lib/python3.9/site-packages/scvi/model/base/_utils.py:66, in _load_saved_files(dir_path, load_adata, prefix, map_location, backup_url)
     64 try:
     65     _download(backup_url, dir_path, model_file_name)
---> 66     model = torch.load(model_path, map_location=map_location)
     67 except FileNotFoundError as exc:
     68     raise ValueError(
     69         f"Failed to load model file at {model_path}. "
     70         "If attempting to load a saved model from <v0.15.0, please use the util function "
     71         "`convert_legacy_save` to convert to an updated format."
     72     ) from exc

File ~/.local/lib/python3.9/site-packages/torch/serialization.py:1529, in load(f, map_location, pickle_module, weights_only, mmap, **pickle_load_args)
   1521                 return _load(
   1522                     opened_zipfile,
   1523                     map_location,
   (...)
   1526                     **pickle_load_args,
   1527                 )
   1528             except pickle.UnpicklingError as e:
-> 1529                 raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
   1530         return _load(
   1531             opened_zipfile,
   1532             map_location,
   (...)
   1535             **pickle_load_args,
   1536         )
   1537 if mmap:

UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint. 
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL numpy.core.multiarray._reconstruct was not an allowed global by default. Please use `torch.serialization.add_safe_globals([numpy.core.multiarray._reconstruct])` or the `torch.serialization.safe_globals([numpy.core.multiarray._reconstruct])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.

**Comment by ori-kron-wis** [comment]
@LitalBarak96 seems you run an old version (as you run python 3.9) . This issue is fixed in a later version of scvi-tools, so I suggest you to just upgrade it in an updated environment.
