### ISSUE TITLE
Integrating multiple datasets for batch effect correction

### ISSUE THREAD

**Issue by cartal** [YosefLab/scVI#196]
Hi, 

I'm really enjoying playing around with my data using the example notebooks. Very nice tool indeed. 

I'm interested in performing batch effect correction in multiple datasets by integrating them into a single object and perform downstream analyses. The same idea behind Seurat CCA analysis.

Is this possible? If so, can you provide an example of the integration step?

**Comment by jeff-regier** [comment]
Hi Carlos, Thanks for trying out scVI! We're in the process of porting some notebooks from Seurat over to scVI. @romain-lopez Do you know if anyone is developing an scVI notebook that does something like Seurat CCA analysis?

**Comment by romain-lopez** [comment]
Yes, this is ongoing ! Stay tuned !

**Comment by romain-lopez** [comment]
@chenlingantelope is there a code snippet we could share as a public notebook for Carlos ? If you point me towards the code I turn it into a nice notebook. There is also the harmonization notebook, not sure where that stands.

**Comment by romain-lopez** [comment]
Back on this, we are finally working out the last details of this notebook. Coming soon

**Comment by haircell** [comment]
Would definitely be great to see a Seurat-like notebook!

**Comment by cartal** [comment]
Any updates on this guys? Or should we refer to scVAN?

**Comment by romain-lopez** [comment]
closed by #275. Thanks for your patience, that was a lot of work to merge everything on our hand

**Comment by cartal** [comment]
Thank you!
