### ISSUE TITLE
Warn users that all-zero cells will be dropped when making GeneExpressionDataset?

### ISSUE THREAD

**Issue by vals** [YosefLab/scVI#198]
Hi,

I was a bit sloppy the other day and simply made a `GeneExpressionDataset` but didn't compare the sizes of my `DataFrame` with annotations and the `X` matrix in the dataset.

After training the model and visualizing the embedding I couldn't match the annotations to the data, I was missing 5 cells!

Figuring out that this was due to `get_attributes_from_matrix` filtering cells with zero expression in all genes didn't take long, but I think it might be a good idea to have a little warning message when that happens so users aren't confused?

Best,
/Valentine

**Comment by jeff-regier** [comment]
Yes, sounds like a good idea. Thanks for the suggestion.

**Comment by vals** [comment]
Thanks!
