### ISSUE TITLE
Importing 10x data

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scVI#200]
I received this email from a user:

> I didn't find command to load local 10X data into scVI.
> 
> In [4]:
> gene_dataset = CortexDataset(save_path=save_path)
> But I want to analyze my data set stored in local hard drive space as mentioned below,
> 
> data/10X/SampleA1/outs/filtered_gene_bc_matrices/mm10
> data/10X/SampleA2/outs/filtered_gene_bc_matrices/mm10
> data/10X/SampleA3/outs/filtered_gene_bc_matrices/mm10
> 
> and then how do I perform the differential test on SampleA1 vs SampleA2 vs Sample A3?

Matthew from the YosefLab told me our data loading notebook was outdated. It would be good to look into that.

Thanks, 
Romain

**Comment by jules-samaran** [comment]
I modified the Dataset10X class to allow someone to load any kind of 10X data that is saved locally, even if it's not in the list of 10X datasets supported by scvi. I added to the notebook the list of datasets that we use but that we hadn't talked about in the data_loading notebook like dropseq, OsmFISH, STARmap, etc.

**Comment by jules-samaran** [comment]
I talked with Matthew and he told me the problem he had was that the pip version was not updated with the github version of scvi so this is not related to this precise issue, I think we can close this
