### ISSUE TITLE
pip install not up-to-date

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scVI#202]
with scVI installed by pip install, the notebooks have run errors. we need the pip package to reflect the last changes to the API.

**Comment by romain-lopez** [comment]
@jules-samaran, would you be able to take care of that now the tox error is solved ? Thanks

**Comment by jules-samaran** [comment]
@jeff-regier I created an account on pypi, all I have to do now is to run these
$ python3 setup.py sdist bdist_wheel
$ twine upload dist/*
once you've granted me the permission to upload the latest version of scVI on pip

**Comment by jeff-regier** [comment]
We've also got to tag a new version on github before uploading it. It's probably better if you, me, and Romain go over the release process we meet next.
