### ISSUE TITLE
scanpy integration

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#206]

**Comment by wangjiawen2013** [comment]
I am familiar with scanpy. How does it goes now ? It's good to integrate scAnvi to scanpy !

**Comment by romain-lopez** [comment]
The project is not going very smoothly on our end. So that might take a while, any chance you would like to contribute @wangjiawen2013 ?

**Comment by wangjiawen2013** [comment]
I am trying to use scvi, I'll reply to you when I familiar with scvi.

**Comment by wangjiawen2013** [comment]
perhaps you and your partners can fork the scanpy integration project on github, then we can add modules to it. @romain-lopez

**Comment by falexwolf** [comment]
I'd love it if we get scVI integration in some way! Such a nice tool! :)

Any chance that the way @gokceneraslan wrapped DCA combined with the way other people wrapped their batch effect correction tools could also work for scVI? I know that the scanpy functional API is not powerful enough to access all of scVI's functionality, but having some limited functionality be exposed very conveniently could be making people's life easier.

I'll have more specific suggestions, soon. ;)
