### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scVI#218]
https://scvi.readthedocs.io/en/master/notebooks/annotation.html

**Comment by jules-samaran** [comment]
This is because we moved the notebooks from `docs/` to `tests/`

**Comment by jeff-regier** [comment]
@romain-lopez  Where did you find that link? I updated the readme to point to the new notebooks, but I excluded the annotation notebook because it's not really done yet.

**Comment by romain-lopez** [comment]
I think that was referenced by Google somewhere. Maybe It'll just disappear. Ok let's stick to these new links in the readme
