### ISSUE TITLE
temporary file to temp directory

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#237]
Hi Jules, Would you write this temporary file to the temporary directory instead of `tests/data`? I know it gets deleted, but it's still better if the unit tests only write to the temp directory.

https://github.com/YosefLab/scVI/blob/da21b7200ff66dc9b36a93b38dbd6258b1ac53df/tests/test_notebook.py#L114

**Comment by jeff-regier** [comment]
Could you change the working directory to `save_path` rather than writing `save_path` to disk? e.g.
```
os.chdir(save_path)
```

Even if what you have now works, it's confusing to create a temporary file outside of the temporary directory just to store a string that is the path to the temporary directory. (Am I understand that correctly?)

**Comment by jules-samaran** [comment]
Yes you understood that correctly, I'm going to look into that
