### ISSUE TITLE
compatibility issue with torch 1.0.0 and GPU?

### ISSUE THREAD

**Issue by byoo** [YosefLab/scVI#242]
I had trouble following a tutorial using scVI with torch 1.0.0 and GPU.
I played with the basic tutorial and an error occurred in plotting tsne as below. FYI, training with CPU didn't cause the error and it looks to be relevant to this change of pytorch; (https://github.com/pytorch/pytorch/pull/10416).

"_can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first._"
https://github.com/YosefLab/scVI/blob/6937e0df9c4b37dad2bc6cef5f2d45f4a9ade656/scvi/inference/posterior.py#L151

Thank you.

**Comment by jeff-regier** [comment]
We've only tested scVI with pytorch 0.4 and 0.4.1 so far. We'll get it working with the newest pytorch release soon.

**Comment by jules-samaran** [comment]
I'm trying to reproduce the issue, I updated torch to 1.0.0 and the tests ran without error even with `use_cuda=True`

**Comment by jeff-regier** [comment]
@jules-samaran I was able to reproduce the errors too, but with the following commands:
```
conda create --name test5
conda activate test5
conda install scvi -c bioconda -c pytorch
make test
```

Above `test5` is the name of a new environment. I'm installing all the dependencies for scvi from the bioconda and pytorch channel (so we install pytorch 1.0). When I run `make test`, the working directory is the `scVI` repo. This is all on a machine with a GPU.

**Comment by jules-samaran** [comment]
I pushed commit 6849c86aa77a1840a1567c4e24ebaf9884ea0947 to add explicitly the conversion to CPU necessary when working on GPU before converting a torch tensor to a numpy array. As @byoo pointed out, this conversion used to be done implicitly before but was removed in torch 1.0.0

**Comment by jules-samaran** [comment]
Thanks a lot for reporting the issue!

**Comment by jeff-regier** [comment]
OK looks good. @jules-samaran Will you open a PR?
