### ISSUE TITLE
How to obtain scaled imputed expression values

### ISSUE THREAD

**Issue by JoelRV** [YosefLab/scVI#247]
Hello,

The procedure provided in the tutorial to obtain imputed values returns a matrix without cell scale correction. How would it be possible to get the scale-normalized data matrix?

Thank you for your great work on the python package.

**Comment by jules-samaran** [comment]
Hi, thank you for raising your concern, I opened a PR to make it simpler to retrieve the cell scale normalized values reconstructed by our model and explained how in the basic tutorial. This will be included in the next release of the package which is coming soon
