### ISSUE TITLE
Imputation Benchmark Error

### ISSUE THREAD

**Issue by asuresh2** [YosefLab/scVI#248]
I keep getting the error:
imputation_benchmark() got an unexpected keyword argument 'save_path'
when I try running it. I'm not sure why because the save_path keyword argument is in the imputation_benchmark function definition, and in posterior.py. Any idea why I'm getting this error?

**Comment by jules-samaran** [comment]
The `save_path` argument in this method was added in a github commit after the release of the latest version of scvi on pypi so this might explain why when you look at the most updated version which is the one on this repository you see `save_path` in the definitions but it still raises an error when you run the code installed on your machine.
@jeff-regier when will we release a new version?

**Comment by romain-lopez** [comment]
I just released scVI 0.2.4. If this is an old version problem, then we can close this issue
