### ISSUE TITLE
File path concatenation can fail

### ISSUE THREAD

**Issue by byoo** [YosefLab/scVI#259]
In loading a 10x run locally, scVI couldn't find the `barcodes.tsv` due to the failure of path concatenation.
I noticed some paths are concatenated using string concatenation. Would you fix those, maybe using `os.path.join()`? Thanks!

https://github.com/YosefLab/scVI/blob/68aaf38ca8c28cccb34f5711115c626a99434955/scvi/dataset/dataset10X.py#L110

**Comment by jules-samaran** [comment]
Thank you a lot for telling us, it seems like this is the only part I had forgotten to fix in my previous commits. All path concatenations should be executed with `os.path.join()` now
