### ISSUE TITLE
Providing batch indices with CsvDataset

### ISSUE THREAD

**Issue by PrimozGodec** [YosefLab/scVI#263]
Sorry for writing that on the issue tracker but I cannot find another way to get a response. If I understand right there is no way to provide batch indices together with CSV data (when using CSVdataset class). So when reading CSV data there is not an option to make a batch correction. 

Am I right or I missed something. Is there any good workaround. Since I am interested in this feature I can open a pull request with the extension of a CSVdataset class, just need confirmation before.

**Comment by romain-lopez** [comment]
Hi, 

Thanks for your interest in scVI. So far there is no direct way of doing that. I recommend adding an argument batch_ids_file=None following what is done with the labels_file argument. That would be a nice contribution to the package !

Thanks, 
Romain

**Comment by romain-lopez** [comment]
Clsoed by PR #264
