### ISSUE TITLE
Cannot install latest release with conda or pip

### ISSUE THREAD

**Issue by Abigail-Wood** [YosefLab/scVI#266]
**Your operating system name and version.**
MacOS 10.13.3

**Any details about your local setup that might be helpful in troubleshooting.**
Running Anaconda Navigator 1.9.6, Python 3.6, attempting to use a Jupyter notebook to run some of the basic scVI tutorial. 

**Detailed steps to reproduce the bug.**
When adding scVI using the command listed in the quick-start guide (conda install scvi -c bioconda), it only added the earliest release (0.1.2), rather than the latest (0.2.4). The same issue occurs with pip. I resolved this by cloning the git repository and running the setup.py file, but cannot get Anaconda to acknowledge this new version.

(I am a relatively new Bioinformatics student, so I apologise in advance if this is an ignorance-based error!)

**Comment by romain-lopez** [comment]
Hi, 

Thanks for pointing this out, that issue looks like a problem. Could you figure something out ? Otherwise, I can push a new version in the next week.

Romain

**Comment by jeff-regier** [comment]
scVI depends on some other software libraries. conda attempts to install the latest version of scVI that is compatible with the libraries you have installed, and perhaps to update the other libraries you have installed. What may be happening is that scVI version 0.1.2 is the most recent version of scVI that is compatible with the rest of your libraries. If you create a new conda "environment" just for scVI, then `conda install scvi -c bioconda` should install the latest versions.

On my system, `conda install scvi -c bioconda` seems to fetch the latest version:
```
$ conda install scvi -c bioconda
Solving environment: done

## Package Plan ##

  environment location: /Users/jeff/miniconda3

  added / updated specs: 
    - scvi


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scvi-0.2.4                 |             py_0          48 KB  bioconda
    urllib3-1.24.1             |           py36_0         149 KB
    ca-certificates-2019.1.23  |                0         126 KB
    requests-2.21.0            |           py36_0          85 KB
    conda-4.6.4                |           py36_0         1.7 MB
    ------------------------------------------------------------
                                           Total:         2.0 MB

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0           --> 2019.1.23-0           
    conda:           4.5.12-py36_0          --> 4.6.4-py36_0          
    requests:        2.14.2-py36_0          --> 2.21.0-py36_0         
    scvi:            0.2.3-py_0    bioconda --> 0.2.4-py_0    bioconda
    urllib3:         1.12-py36_0   bioconda --> 1.24.1-py36_0         

Proceed ([y]/n)? 
```

**Comment by romain-lopez** [comment]
Hi, I just pushed scVI v0.3.0 and it was probaby a packages conflict as underlined by Jeffrey. Closing the thread.
