### ISSUE TITLE
Imputed expression level in the same dimension as input matrix.

### ISSUE THREAD

**Issue by jmbreda** [YosefLab/scVI#284]
Dear author,

To obtain the imputed expression levels of each gene and in each cell, is the correct procedure to set the parameter _new_n_genes_ to the actual number of genes in the input table when loading the data? If so, are the rows and columns sorted identically to the input matrix?

Thanks!

**Comment by romain-lopez** [comment]
Hi, 

Depending on how you load the data, there might be a default parameter that filter some of your genes. You might want to adjust this parameter to make sure you use the whole dataset.  You can send me some code here if you would like to make sure.

To make sure the imputed values are sorted, you need to create a sequential posterior as we present in the various notebooks.

Best, 
Romain

**Comment by jmbreda** [comment]
Dear Romain,

Thanks a lot for your answer.

I load the data using the following command:
`local_csv_dataset = CsvDataset(in_file,save_path='data/',compression='gzip',new_n_genes=N_gene)`
with _N_gene_ the number of genes (i.e. rows) in the input raw count table.

So I assume that creating a sequential posterior is done with the following command:
`imputed_values = full.sequential().imputation()`

For some context, here is the entire script:
```
dataset = 'Grun_ESC/SC_2i'
in_file = 'Grun_ESC_SC_2i.csv.gz'
N_gene=12535

# 1) load data
from scvi.dataset import  CsvDataset

local_csv_dataset = CsvDataset(in_file,save_path='data/',compression='gzip',new_n_genes=N_gene)

# 2) process data
import os
import numpy as np
import pandas as pd
from scvi.models import *
from scvi.inference import UnsupervisedTrainer
import torch

use_batches=False
use_cuda=True
n_epochs = 400
vae = VAE(local_csv_dataset.nb_genes, n_batch=local_csv_dataset.n_batches * use_batches)
trainer = UnsupervisedTrainer(vae, local_csv_dataset, train_size=0.75, use_cuda=use_cuda)
trainer.corrupt_posteriors(rate=0.1, corruption="uniform")
trainer.train(n_epochs)
trainer.uncorrupt_posteriors()
full = trainer.create_posterior(trainer.model, local_csv_dataset, indices=np.arange(len(local_csv_dataset)))
imputed_values = full.sequential().imputation()

# 3) print imputed values
np.savetxt('data/' + dataset + '/scvi_count.txt',imputed_values.T,fmt='%.6e',delimiter='\t')
```

Thanks again for making this tool available!

Best,
Jeremie

**Comment by romain-lopez** [comment]
Hi Jeremie, 

trainer.corrupt_posteriors(rate=0.1, corruption="uniform")
trainer.train(n_epochs)
trainer.uncorrupt_posteriors()

these lines of code (corrup_posteriors and uncorrupt_posterior) are only to *benchmark* imputation algorithms as we did in the paper. I invite you to remove these lines of code. 

Also, as you can see from the csv.py file: self.subsample_genes(new_n_genes, subset_genes). So your usage for new_n_genes set to the number of gene from the file is indeed correct. 

Best, 
Romain

**Comment by jmbreda** [comment]
Thanks a lot for your help Romain, it's quite faster without those lines!

Best,
Jeremie
