### ISSUE TITLE
Different results

### ISSUE THREAD

**Issue by fedeago** [YosefLab/scVI#286]
Dear author, i am using scvi to do batch correction and then i am doing Clustering on the latent space. If i run the same model multiple times with the same hyperparameters on the same data i obtain different output probably due to the fact that i reached different local minimun. How can i find the value of the objective function to be sure that i have not reach a local minimun?

**Comment by romain-lopez** [comment]
You can compute the held_out log likelihood (trainer.test_set.ll()) and keep the model with the better one?

**Comment by fedeago** [comment]
yes but i can not tuning the hyperparameters becouse i have always a different output model. Is there a way to set a seed in order to have the same latent rapresentation with the same hyperparameters?

**Comment by fedeago** [comment]
i will try to average the results. Thank you.
