### ISSUE TITLE
fixed_batch in get_harmonized_scale

### ISSUE THREAD

**Issue by uhcnivag** [YosefLab/scVI#287]
Hi Romain,
    Thanks for your previous answers that get_harmonized_scale(fixed_batch) shows normalized and batch-corrected data matrix. May I know the meaning of parameter fixed_batch and what value(s) is suggested to be the input? Thanks!   -Sky

**Comment by romain-lopez** [comment]
You can think about this parameter fixed_batch as a calibration process. It will impute all the cells as if they were all sequenced within batch "fixed_batch". If you have a reference batch, you can use that one. Otherwise any of them is good.

**Comment by uhcnivag** [comment]
I see! Thanks a lot!

**Comment by romain-lopez** [comment]
closed due to inactivity
