### ISSUE TITLE
conditional instance normalization

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#292]
This technique might be helpful for merging datasets (harmonization):
https://arxiv.org/pdf/1610.07629.pdf

We wouldn't have to rely on adversarial mechanisms so much (at all?) if we use a less flexible generative model that can nonetheless represent datasets drawn from different distributions.

**Comment by jeff-regier** [comment]
Hi Achille, Feel free to close this issue if the paper turns out not to be helpful for your smFISH harmonization work -- but I think it might work really well!

**Comment by gabmis** [comment]
@ANazaret can we close this?

**Comment by jeff-regier** [comment]
Did conditional instance normalization work for us? If not, let's close it. If it worked, let's close it once the PR is merged.

**Comment by ANazaret** [comment]
From what I've tested, conditional instance normalization is too flexible and the model can mix the datasets without biological coherence in the latent space.
