### ISSUE TITLE
No lables, cell_types, batches in AnnDataset()

### ISSUE THREAD

**Issue by raevskymichail** [YosefLab/scVI#298]
HI! I followed your basic tutorial with my `.h5ad` and I'm stacked on applying **`show_t_sne()`** when **`color_by='labels'`** is specified, because no label is shown. Looks like even if it's possible access to `gene_dataset.obs`, **`show_t_sne()`** is accept a `gene_dataset.cell_types` instead of `gene_dataset.obs.cell_types`. What probably causes the problem:

```python
# Inside show_t_sne.
if hasattr(self.gene_dataset, 'cell_types') and color_by == 'labels':
                    plt_labels = self.gene_dataset.cell_types
```

I looked throught **`AnnDataset()`** and **`CortexDataset()`** source code and found that `cell_types` and `labels` aren't processing in **`AnnDataset()`**:

**`AnnDataset`** :
```python
        if type(filename_or_anndata) == str:
            self.download_name = filename_or_anndata
            self.save_path = save_path
            self.url = url

            data, gene_names = self.download_and_preprocess()

        elif isinstance(filename_or_anndata, anndata.AnnData):
            ad = filename_or_anndata
            data, gene_names = self.extract_data_from_anndata(ad)
```
**`CortexDataset`**  :
```python
        self.additional_genes = additional_genes
        expression_data, labels, gene_names, cell_types = self.download_and_preprocess()

        super().__init__(
            *GeneExpressionDataset.get_attributes_from_matrix(
                expression_data,
                labels=labels),
            gene_names=np.char.upper(gene_names), cell_types=cell_types)
```
Is there any solution for this problem?

_Originally posted by @raevskymichail in https://github.com/YosefLab/scVI/issues/254#issuecomment-484653431_

**Comment by romain-lopez** [comment]
Hi, 

Thanks for your interest in scVI,
I guess you need to modify the function extract from AnnData and add the option to extract the labels by giving it in argument the covariate string.

You can also manually add the labels to the GeneExpression dataset object (please refer to our new scanpy notebook).

Best,
Romain

**Comment by gabmis** [comment]
@romain-lopez Much like the `scvi.dataset.loompy` class:
```
        if 'Gene' in ds.ra:
            gene_names = ds.ra['Gene']

        if 'BatchID' in ds.ca:
            batch_indices = ds.ca['BatchID']
            batch_indices = np.reshape(batch_indices, (batch_indices.shape[0], 1))[select]

        if 'ClusterID' in ds.ca:
            labels = np.array(ds.ca['ClusterID'])
            labels = np.reshape(labels, (labels.shape[0], 1))[select]

        if 'CellTypes' in ds.attrs:
            cell_types = np.array(ds.attrs['CellTypes'])
```
we could take several keys in order to retrieve the labels, cell types, etc from the anndata object. Since there is no guaranteed structure, we could leave them to the user as arguments in `AnnDataset.__init__`.

**Comment by romain-lopez** [comment]
yes, that looks like a great option

**Comment by raevskymichail** [comment]
HI!
For myself I solved this problem about the same way as @gabmis referred by making `AnnDataset()` behavior more similar to the `LoomDataset()`. Please, see and review modified `anndata.py`
