### ISSUE TITLE
How to choose model for normalized data？

### ISSUE THREAD

**Issue by QqQss** [YosefLab/scVI#301]
I want to harmonize several data from different study, but for some study I can only download its normalized matrix (TPM or CPM). 

As you mentioned, scVI expected inputs are raw counts because of assumption of ZINB in your generative model. 

In my case, the most of inputs are raw counts, but there are several inputs are pre-normalized matrix (1/5 or 1/6 in total). Can I use scVI anymore? 

If the answer was yes, how do I set the parameters in order to better suit my inputs?

**Comment by QqQss** [comment]
BTW,  why not to add log-norm distribution as a alternative option in generative model?  Because these normalized values may be more likely as log-norm distribution  (Reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1240081/).  I guess the single cell's version is ZI (zero inflated)  log-norm.

Anyway, would you consider that add this distribution in the future?

**Comment by romain-lopez** [comment]
Hi, 

there is not a way to use normalized values in scVI yet. You can:
+ add your own loss here  https://github.com/YosefLab/scVI/blob/master/scvi/models/log_likelihood.py
+ add your own class to our package (if log normal, then there might be no need for library size scaling) in scVI.models

**Comment by vals** [comment]
Hey @QqQss 

I've encountered this with public data too sometimes. If the data that was transformed was UMI based, I have found an "unnormalization" strategy that works pretty well: http://www.nxn.se/valent/2018/10/25/unscaling-scaled-counts-in-scrna-seq-data

It doesn't work well for full-length non-UMI data like Smart-seq2 or SMARTer however.

And of course it is always better to have the actual counts. I usually send an email to the authors asking if I can get their count matrix before scaling it, and they are usually happe to send it.

**Comment by QqQss** [comment]
@romain-lopez 
Thanks for your reply.  I think If log-norm, then there may also need estimate L space which is not only stand for library size but also some others unwanted variables.
Even if someone did routinely normalization, i.e. TPM or CPM,  these rough methods cannot remove all these unwanted biases ..

**Comment by QqQss** [comment]
@vals 
Thanks for your suggestion. Maybe the most likely I could do is to contact with these authors ...  :)
