### ISSUE TITLE
confusion matrix for classification of zeros with synthetic data

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#303]
With simple-but-non-trivial synthetic data, let's test that scVI correctly classifies zeros as either biological (i.e., the expression level really is low) or technical (i.e., due to a "dropout" event). Results could be reported as a confusion matrix.

It'd also be nice to make the code for this experiment into a test within the `tests` directory -- basically we want to test that scVI usually predicts biological vs technical correctly. It would be a long-running test since each time we have to train a model, so it can't run on travis-ci. We can skip it by default this way:
https://docs.pytest.org/en/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option

**Comment by PierreBoyeau** [comment]
Hi Jeff, 
Based on the PR #304 and script [here](https://github.com/PierreBoyeau/scVI/blob/synthetic/tests/test_zeros_synth.py#L43) we came up with the following protocol:

- We define a ground-truth zero cell-gene entry in our synthetic dataset to be "technical" when the ZI mask is zero on it, and as "biological" when the zero comes from the Poisson distribution sampling and the mask is not zero on it.

- We define the classification of a cell-gene entry as zero when we observe after sampling the posterior predictive a majority of cases where zeros come from ZI rather than the NB.

We have still some issues to fix, but do you approve this protocol?
O&P

**Comment by jeff-regier** [comment]
That sounds almost perfect.

I'd instead define technical zeros based on the underlying rate parameters to the Poisson distribution: technical zeros are from expressed genes (the "marker" genes we discussed -- the "high" ones) and biological zeros as the zeros from the rest. That way the ground truth for our classification problem is defined by the underlying expression level and not subject by random variation.

One benefit of this definition: scVI should get almost a perfect score -- i.e. only true-positives and true-negatives -- so it's a good "functional test". With the other definition, we'd expect scVI to do well, but if it didn't get everything right, we wouldn't be sure whether something was off or whether that's just the best any algorithm could do.

This definition also deals with the otherwise troubling case where a zero is due to both Poisson noise *and* masking.

Or at least that's my current thinking -- I'm excited to see how it turns out!

**Comment by jeff-regier** [comment]
We may need to make some minor adjustments to the procedure for generating synthetic data to ensure it has a non-trivial number of zeros from each class (technical and biological). If the gene expression for the marker genes is too high (either due to large library size or high Poisson rate parameters for these genes) then there won't be any biological zeros. Reducing the library size may may increase the number of biological zeros, but if we decrease it too much, the infrequently expressed genes will only be observed as zeros, which is OK but not ideal for testing. Adjusting the relative expression level of marker to non-marker genes, to get a roughly equal number of zeros from each class, probably would work better.
