### ISSUE TITLE
How does scVI use video memory?

### ISSUE THREAD

**Issue by QqQss** [YosefLab/scVI#306]
Hi, guy, I‘ll brother you again :) 

My question now is how does scVI use video memory. 

When we input the data, we first load the input into memory. The memory could be very large, hundreds even thousands of gigabyte, which permit us handle very large data. 
Then if we want to use a GPU to calculate, the compute will transform the input from memory to GPU's video memory, right? But in most case, GPU only have a small memory capacity. How does it work?

So my question is: Does scVI transform each mini-batch one by one into GPU memory, calculate, then release? or transform the whole dataset at once?

I have just been engaged in ML recently and maybe this is a stupid question in the field... forgive me.

**Comment by jeff-regier** [comment]
We use the pytorch library for data loading -- it really handles all these details for us. Basically at any given time the neural network is stored in the GPU memory, as well as one mini-batch of cells. So the former: one by one.
