### ISSUE TITLE
Differential Expression

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#309]
We should compare performing a DE test on the `rho` values to a test on the `w` values, which are the samples from the gamma. 

It looks like we can calculate in [closed form](https://math.stackexchange.com/questions/2426140/probability-of-a-gamma-r-v-greater-than-another) the probability that `w_a > w_b` for cells `a` and `b` and for the same gene `g` because they have the same rate (`theta` in the context of scVI)

**Comment by jeff-regier** [comment]
@PierreBoyeau I'd be glad if you'd think about this issue, and perhaps talk to @romain-lopez about what we've done so far detecting differential expression. There's room for improvement! Getting another test in place with synthetic data, like what you Oscar developed for #303, but this time for differential expression might be a good way to start.

**Comment by romain-lopez** [comment]
I'm working on DE for scANVI revision, I can also share some of my thoughts on estimators and divergences etc.. Let's talk soon Pierre

**Comment by PierreBoyeau** [comment]
As we've discussed I'd love to work on that. Thanks!

**Comment by jeff-regier** [comment]
Excellent. #290 and #291 maybe helpful if you find the current DE detection lacking. If they aren't helpful feel free to close those issues.
