### ISSUE TITLE
Storing latent parameters

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#311]
I'm still getting acquainted with the `Posterior()` functionality, but it seems like we can make an improvement if we have the class store the latent parameters. It seems like there are many functions which use these latent parameters but have to pass the entire dataset through the encoder every time.

For example, one could access the latent mean like this:

`posterior.latent_params['qz_m']`

**Comment by jeff-regier** [comment]
We may want to have a meeting sometime with everyone working on scVI to talk about ways to refactor the codebase. I think it's pretty good shape now but I'd like to make it even better.

**Comment by jeff-regier** [comment]
Closed, based on discussion today at the weekly scVI team meeting
