### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#313]
I just installed my clone in a fresh virtual environment. 

I get the following import error

ImportError: cannot import name 'IndexMixin' from 'scipy.sparse.sputils' (/Users/adamgayoso/.virtualenvs/scvi/lib/python3.7/site-packages/scipy-1.3.0rc1-py3.7-macosx-10.14-x86_64.egg/scipy/sparse/sputils.py)

It has to do with the scanpy integration.

**Comment by adamgayoso** [comment]
It looks like the issue has to do with the scipy version. Scipy 1.2.1 is the current release and in requirements.txt so I'm curious how scipy 1.3.0 got installed.

**Comment by jeff-regier** [comment]
Looks like you had a pre-released verision of scipy: 1.3.0rc1

**Comment by adamgayoso** [comment]
Right, but I installed in a virtualenv and don't have this prerelease version installed globally so something must have triggered this install.

**Comment by jeff-regier** [comment]
I tried with a fresh install of miniconda. I get scipy version 1.2.1, not 1.30rc1.

```
(base) jeff@milkyway:~/git/scVI$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
```

**Comment by jeff-regier** [comment]
Closed, based on discussion today at the weekly scVI team meeting
