### ISSUE TITLE
New 10X Data

### ISSUE THREAD

**Issue by PierreBoyeau** [YosefLab/scVI#314]
For the DE task one of the idea, along with synthetic datasets is to use datasets such as this one 
https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/hgmm_5k_v3

This made me realize there was a quantity of datasets (all cell ranger 3.0.0) which were not included in the current pipeline. As a reminder, you can find the list of all datasets [here](https://support.10xgenomics.com/single-cell-gene-expression/datasets)

My guess is that they are new, but maybe there were knowingly ignored. Is there interest in adding these datasets to scVI?

I am currently working on extending the `Dataset10X` dataset to include them, so if you think we should add these datasets I'd gladly do a PR.

**Comment by PierreBoyeau** [comment]
And @jeff-regier @adamgayoso there are some scRNA/surface proteins datasets in these datasets.
Are those the ones you mentionned last week?

https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_1k_protein_v3
https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_10k_protein_v3
https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/malt_10k_protein_v3

**Comment by jeff-regier** [comment]
I may have mentioned the two 10k-cell datasets before. Sure, adding them sounds good. I think they're different than what Adam was using.
