### ISSUE TITLE
Deprecated diff exp function?

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#317]
It's not clear to me what the purpose of this function is. It doesn't seem to be used for anything else and it is a bit confusing because the doc string is incorrect and the output is not sequential.

https://github.com/YosefLab/scVI/blob/1584b9ef3c21b77d3feb88a6a4727a9f389fd963/scvi/inference/posterior.py#L172

**Comment by jeff-regier** [comment]
It doesn't look like it's used in any of our notebooks either -- not even the one that recreates the results of the original scVI paper.

@romain-lopez Does this function look at all familiar to you?

If this function isn't doing anything useful any more, it'd be great to delete it.

**Comment by romain-lopez** [comment]
yes, we use a modified version of this function in the scANVI paper but I am not sure that one is absolutely necessary. In particular, we are probably going to need to design a more flexible API with people are going to want to use scVI and scANVI for DE with respect to multiple batches.

**Comment by jeff-regier** [comment]
Maybe it would be best if @PierreBoyeau removed (or revised) this function as part of his work on DE?

In general I think we want all the code in the `scvi` directory to get executed by running the notebooks. But `differential_expression_stats` isn't called by any notebook.

**Comment by romain-lopez** [comment]
yes, this is what I was thinking about !

**Comment by PierreBoyeau** [comment]
Sure it makes sense!

**Comment by romain-lopez** [comment]
to change the docstring

**Comment by romain-lopez** [comment]
fixed by #354
