### ISSUE TITLE
conda installs outdated version of pytorch

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#322]
[Our current bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/594e7d2c54459fd7d9c9db601f9e77656d7650fc/recipes/scvi/meta.yaml) installs Pytorch 0.4.1 when scVI is installed.

It'd be nice if we could make pytorch a test requirement somehow, or, better yet, pytorch-cpu. And then not automatically install pytorch when a user runs `conda install scvi`.

**Comment by jeff-regier** [comment]
We probably need conda to install the `mongodb` and the `hyperopt` packages now too.

**Comment by jeff-regier** [comment]
I'm trying it: bioconda/bioconda-recipes#15220

**Comment by jeff-regier** [comment]
Huzzah! It works. Pytorch is no longer required by conda to install scVI. Turns out it's not necessary to list every package scVI might use as a conda requirement -- just the ones needed for `import scvi` to  run without errors.

@romain-lopez

**Comment by romain-lopez** [comment]
Youhou !
