### ISSUE TITLE
Large local datasets in hyperparameters autotuning

### ISSUE THREAD

**Issue by raevskymichail** [YosefLab/scVI#325]
HI! 
First, thank you for developing the __hyperopt__ solution for hyperparameters optimization.
Unfortunately, I am faced with the following problem while applying `auto_tune_scvi_model()` on my local dataset.
The snippet I ran:
```python
import logging
logger = logging.getLogger("scvi.inference.autotune")
logger.setLevel(logging.WARNING)

# set high n_epochs since default behaviour has early stopping
n_epochs = 1000 if n_epochs_all is None else n_epochs_all
max_evals = 1000 if n_epochs_all is None else 5

best_trainer, trials = auto_tune_scvi_model(
    gene_dataset=GSE96769_dataset,
    parallel=True,
    exp_key="exp1",
    train_func_specific_kwargs={'n_epochs':n_epochs},
    max_evals=max_evals
)
```
Which returned an error:
```
  0%|          | 0/1000 [00:00<?, ?it/s][2019-05-10 09:27:24,368 - fmin Process - MainThread] ERROR - scvi.inference.autotune
Caught ('cannot serialize a bytes object larger than 4 GiB',) in _fmin_parallel, starting cleanup
Traceback (most recent call last):
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/scvi/inference/autotune.py", line 140, in decorated
    return func(*args, **kwargs)
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/scvi/inference/autotune.py", line 594, in _fmin_parallel
    show_progressbar=show_progressbar,
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 388, in fmin
    show_progressbar=show_progressbar,
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/hyperopt/base.py", line 639, in fmin
    show_progressbar=show_progressbar)
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 405, in fmin
    show_progressbar=show_progressbar)
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 126, in __init__
    msg = pickler.dumps(domain)
OverflowError: cannot serialize a bytes object larger than 4 GiB
Process fmin Process:
Traceback (most recent call last):
  File "/home/mraevsky/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/mraevsky/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/scvi/inference/autotune.py", line 140, in decorated
    return func(*args, **kwargs)
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/scvi/inference/autotune.py", line 594, in _fmin_parallel
    show_progressbar=show_progressbar,
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 388, in fmin
    show_progressbar=show_progressbar,
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/hyperopt/base.py", line 639, in fmin
    show_progressbar=show_progressbar)
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 405, in fmin
    show_progressbar=show_progressbar)
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 126, in __init__
    msg = pickler.dumps(domain)
OverflowError: cannot serialize a bytes object larger than 4 GiB
[2019-05-10 09:28:31,307 - MainProcess - MainThread] ERROR - scvi.inference.autotune
Queue still empty 60.0 seconds after all workers have died.
Terminating minimization process.
[2019-05-10 09:28:31,310 - MainProcess - MainThread] ERROR - scvi.inference.autotune
Caught ('Queue still empty 60.0 seconds after all workers have died. Check that you have used a new exp_key or allowed a higher max_evals',) in auto_tune_scvi_model, starting cleanup
Traceback (most recent call last):
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/scvi/inference/autotune.py", line 537, in _auto_tune_parallel
    trials = queue.get(timeout=fmin_timeout)
  File "/home/mraevsky/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/scvi/inference/autotune.py", line 140, in decorated
    return func(*args, **kwargs)
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/scvi/inference/autotune.py", line 315, in auto_tune_scvi_model
    multiple_hosts=multiple_hosts,
  File "/home/mraevsky/miniconda3/lib/python3.7/site-packages/scvi/inference/autotune.py", line 546, in _auto_tune_parallel
    "a higher max_evals".format(fmin_timeout=fmin_timeout)
scvi.inference.autotune.FminTimeoutError: Queue still empty 60.0 seconds after all workers have died. Check that you have used a new exp_key or allowed a higher max_evals
```
The problem, apparently, occurred because of one of the two reasons:
1. MongoDB wasn't well configured, since I'm new to it.
So after MongoDB installation I simply created its new daemon process (mongod) inside `scvi_db` dir:
```shell
mkdir scvi_db
mongod --dbpath ~/scvi_db --port 1234 --directoryperdb --fork --journal --logpath log.log --noprealloc
```
If that is the source of the problem, please, comment what steps should be taken before using `auto_tune_scvi_model()`

2. Python 3.6 multiprocessing problem, since we have:
```OverflowError: cannot serialize a bytes object larger than 4 GiB```
Some relevant links:
https://stackoverflow.com/questions/51562221/python-multiprocessing-overflowerrorcannot-serialize-a-bytes-object-larger-t
https://stackoverflow.com/questions/29704139/pickle-in-python3-doesnt-work-for-large-data-saving

**Comment by gabmis** [comment]
Hi @raevskymichail , thank you for trying out our new autotuning feature!

From the traceback, It doesn't seem like you problem is with MongoDb.

Apart from actually installing MongoDb on your computer, you shouldn't have to do anything. 

In order to reproduce I need more information about ``GSE96769_dataset`` ? Primarily, what is the size of your dataset?

**Comment by gabmis** [comment]
I managed to reproduce with the following.

```python
import pickle

from functools import partial

from hyperopt.base import Domain
from scvi.inference.autotune import _objective_function
from scvi.dataset import GeneExpressionDataset

test = np.zeros((4 * int(1e4), 3 * int(1e4)))
gene_dataset = GeneExpressionDataset(test, None, None, None, None)
fn = partial(_objective_function, {"gene_dataset":gene_dataset})
d = Domain(fn=fn, expr={'foo':'bar'})
msg = pickle.dumps(d)
```

What happens is that hyperopt pickles the objective function for communication between fmin and the workers. But the objective function we have carries the data as a default argument. Thus, if you have a big dataset (> 4Gb) you will get the aforementioned error.

A possible workaround is to build your own objective function and pass it to ``auto_tune_scvi_model`` (I will shortly submit a PR to allow such an argument).

Also, you could try to reduce the size of your dataset. is your dataset sparse? If so are you using a sparse representation (e.g ``scipy.sparse.csr_matrix`` ) ?

**Comment by jeff-regier** [comment]
Could each worker read the dataset from disk, rather than serializing it?

**Comment by gabmis** [comment]
That's a possibility I think.
Inside the objective function we want to have a ``GeneExpressionDataset`` object to use for training. Do we have a generic loader that transforms data into a ``GeneExpressionDataset``without presuming of the way the data is stored?

**Comment by jeff-regier** [comment]
I think we'd just want each process to load the original dataset again -- not some intermediate format

**Comment by gabmis** [comment]
Yes I agree - the user should just input a path to where the data is stored -  my point is that we don’t know in what format the user’s data is stored (h5ad, mtx, csv, npz, etc).

**Comment by jeff-regier** [comment]
It seems like the information is available. If we can load the data in the right format when we're using just one process, can't we do it multiple times with multiple processes?

**Comment by gabmis** [comment]
We‘re not actually loading the data we take a scvi.GeneExpressionDataset as input. What we could do is keep the current input, write the attributes of the GeneExpressionDataset (dataset, labels, etc) to disk and then load them back in each worker prowess. Though that would mean making a copy of a potentially large dataset on disk..

**Comment by jeff-regier** [comment]
The `GeneExpressionDataset` class doesn't load the data until `download_and_preprocess()` is called. Perhaps the solution is to avoid calling `download_and_preprocess()` until later, so that your autotune can serialize a `GeneExpressionDataset` before it's been populated with all the data.

**Comment by gabmis** [comment]
We could try sthing like adding a ``load_later`` argument to the ``GeneExpressionDataset`` subclasses to prevent the call to ``download_and_preprocess`` and add a ``populate`` method to fill the data attributes after instantiation. This would mean changing all the subclasses of ``GeneExpressionDataset`` and may require a little more thinking since I don't all the subclasses yet.
Or instead of a ``GeneExpressionDataset`` instance we could take a ``GeneExpressionDataset`` subclass as input along with the arguments to instantiate it in a ``gene_dataset_kwargs`` argument - then, we'd only perform the instantiation inside each process.
At least, both of these wouldn't work with the ``AnnDataset`` class when it is instantiated with an already existing AnnData object. This can happen, e.g, when a user interfaces ``scVI`` with ``scanpy`` like in ``scVI``'s  scanpy_pbmc3k notebook.

**Comment by jeff-regier** [comment]
It'd be good of none of the subclasses of `GeneExpressionDataset` loaded data automatically upon being instantiated. That should make some things easier in addition to helping with the autotune code.

**Comment by jeff-regier** [comment]
Not sure we'd need to worry about the case of multi-GPU hyperparameter optimization with dataset objects that are already loaded/populated. (E.g. the anndata objects created from another anndata object) For these cases, the user can just write the dataset to disk beforehand.

**Comment by gabmis** [comment]
It's a longer fix but if you really think it's a good idea I can look into it this week

**Comment by jeff-regier** [comment]
I think it's the way to go if we're going to support multiple GPUs for hyperparameter optimization. I'll admit, I underestimated all that was involved in getting multi-GPU working. But if we're close now, still good to see it through.

**Comment by gabmis** [comment]
@raevskymichail Have you been able to solve this issue? If it's not already the case, you could try using a sparse representation of your data.

**Comment by raevskymichail** [comment]
@gabris Unfortunately, I'm still trying to manage with that. My dataset seems quite usual: 1897x19901 cells per genes sparce matrix.

I tried several ways of reduction of my dataset including `sparce.scr_matrix` you mentioned but still have this error.

@jeff-regier I guess, my second question would be whether it's possible to use multiple GPUs. So it will be really great if there will be such option

**Comment by gabmis** [comment]
@raevskymichail actually that's not a large dataset, even in dense format it shouldn't exceed 1Gb. How much space does it take on disk?
Given this new information, I'm not so sure what's happening. Could you provide a snippet of how you load your data?

To answer your question, if you have multiple-gpus on a single machine `auto_tune_scvi_model` 's default beahviour is to use all of them!

**Comment by raevskymichail** [comment]
@gabmis Sorry for missing one important thing:
Actually I have 2 notebooks for different parts of  `GSE96769` dataset: 
+ one for scRNAseq matrix (1897x19901) - 0.89Gb
+ and second for scATACseq matrix (1897x489671) - 5.4GB
And I download them as follows:
```python
GSE96769_dataset = AnnDataset("GSE96769_scATACseq_dataset.h5ad", #or GSE96769_scRNAseq_dataset
                               new_n_genes=False,
                               save_path = save_path)
```
So aforementioned error (`cannot serialize a bytes object larger than 4 GiB` + `FminTimeoutError: Queue still empty 60.0 seconds after all workers have died. Check that you have used a new exp_key or allowed a higher max_evals`) occurs completely while using `auto_tune_scvi_model` on scATACseq matrix.
But even if I use it on the scRNAseq dataset, I still have an error like `FminTimeoutError: Queue still empty...`. Unfortunately, randomly changing `exp_key` and set higher `max_evals` doesn't seem to be a solution. Also, as expected, setting `fmin_timeout = None` just leads to an infinite process with 0% status bar.

**Comment by gabmis** [comment]
I am currently working on your first problem (with scATACseq data)

For your second issue.
Are you running the code snippet on a remote instance inside a notebook? If so, you shouldn't rely on the output since jupyter notebook output breaks quite easily https://github.com/jupyter/notebook/issues/1150 . To know where you are in the autotune process or for diagnosis purposes, check the logs in `scvi_autotune_logfile.txt`.
For me to be able to help you further can you please attach these logs to our discusion.
