### ISSUE TITLE
inconsistent code in posterior get_latent

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#331]
It seems like this function could be cleaned up. Instead of this

https://github.com/YosefLab/scVI/blob/ebd36c1bd6a5dc5336a661404d7dc90e85cc334a/scvi/inference/posterior.py#L153

One could do something like

`latent += [self.model.sample_from_posterior_z(sample_batch, give_mean=True).cpu()]`

I believe this would make the code more readable.

**Comment by jeff-regier** [comment]
I'm not sure I follow precisely what you're proposing...are you just talking about modifying just line 153? Or the whole function that contains line 153?

But no matter: I'd welcome any PR that makes the code more readable! It'll be easiest for me to verify that the change is beneficial if you propose it in a PR, where I can see precisely what lines we're revising.
