### ISSUE TITLE
refactor GeneExpressionDataset

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#337]
`GeneExpressionDataset` is getting pretty messy. Currently, the constructor takes the already loaded data as arguments:
https://github.com/YosefLab/scVI/blob/221cf0fe3b392f0b592aa8040dce4870a0dd908b/scvi/dataset/dataset.py#L23-L24

It'd be preferable for the constructor to take no (or almost no) arguments. Instead, we'd add a new method like this:
```python
    def load(self): ...
```
Notice that the `load(...)` method isn't called with `local_means` and `local_vars`. Instead, it computes `local_means` and `local_vars` by calling `get_attributes_from_matrix(...)` itself. 

The `load(...)` method should also call `download_and_preprocess()` near its beginning.

The method `get_attributes_from_matrix` doesn't need to be called from anywhere besides the `load(...)` method. Currently all the subclasses of `GeneExpressionDataset` call this method before calling `GeneExpressionDataset.__init__()`. But that is duplicated code -- an anti-pattern. And it's confusing because the child class is using a static method of the parent class to generate the data structures it needs in order to instantiate the parent class.

In addition to keeping our codebase readable, adding this `load(...)` method to `GeneExpressionDataset` should help us with issue #325, and perhaps with #270.

**Comment by jeff-regier** [comment]
@gabmis It'd be great if you could address this issue along with #325 

We can put off talking about the spatial stuff until next week if you'd prefer, or I can come by this afternoon.

**Comment by gabmis** [comment]
@jeff-regier I'll gladly do it, let's meet next week then.
@romain-lopez  I'll release after this is done

**Comment by gabmis** [comment]
Hi Jeff, apart from what we need in autotune, I am not sure how you justify the need for a load method, can you explain a bit more please?

Also, from taking a closer look at things, if feel that `get_attributes_from_matrix` and `get_attributes_from_list` should just be `class_method`. We can then use these in the __init__ of the sub-classes.

To be perfectly honest, the dataset subclasses don't really have a reason for existing. They just implement a preprocess method which isn't implemented in the parent class - and it shouldn't be - but is called, by self.download_and_preprocess - which is in the parent class... This is very confusing code and IMO we should just have a `GeneDatasetExpression` without a download_and_preprocess  method -  those things should be implemented inside specific functions dedicated to each data type which would return a `GeneExpressionDataset` built using either the standard `__init__`,a `from_matrix` class_method or a `from_list` class_method.

Also, for the autotune process, having a `load` method doesn”t absolve us from passing the dataset as an argument (to the very `load` method). Having the process load the data from disk is somewhat of an unrelated problem. IMO we’d actually want to tell users who have abnormally big datasets to use subclasses of `GeneExpressionDataset` that do load their data from disk (e.g `AnnDataset`).

What's your opinion on this?

**Comment by jeff-regier** [comment]
I certainly had autotune in mind. The main other issue is that out dataset classes have turned into spaghetti code. 

Oops, the `X` as an argument to `load` was a typo.

Good to avoid most static methods: https://simpleprogrammer.com/static-methods-will-shock-you/

**Comment by jeff-regier** [comment]
Hmm... I haven't worked this out entirely. I don't think getting rid of the subclasses of GeneExpressionDataset is the solution. Perhaps `load()` doesn't need any arguments. It just calls `download` and `preprocess` (implemented by the subclasses), and then sets fields like `_X` based on what preprocess returns.

**Comment by gabmis** [comment]
> I certainly had autotune in mind. 
Then this is not going to solve our problem unless you want all datasets to load from disk

> The main other issue is that our dataset classes have turned into spaghetti code.
I agree and so has `GeneExpressionDataset`. It has a `download` method all the while not having a `url` attribute. It has a `download_and_preprocess` method while not having an implemented preprocess methods - which wouldn't make sense anyway..

> Oops, the X as an argument to load was a typo.
Hardly seems possible, not having X there - i.e having a path to the data instead - would mean that all data should be loaded from disk which seem like a pretty annoying restriction.

> I don't think getting rid of the subclasses of GeneExpressionDataset is the solution.
IMO it could be in the possible solutions. Actually that's what's done in `scanpy` and `scikit-learn`. `scanpy` has a `AnnData` base dataset class and for the various datasets they expose, they provide functions which load a specific dataset into an `AnnData` object. `scikit-learn` does pretty much the same with a simpler `Bunch` dict-like object that is used to represent a dataset.
Still, I understand that this would be a heavy API change.

If we want to keep the code object-oriented, I would suggest having a base `@abstract_class` `GeneExpressionDataset` with all the constructors and common methods of subsampling etc.. Having two child classes :

- one, `DownloadableDataset` which would implement download and be for downloadable datasets 

- and another, `CustomDataset` which wouldn't and would be used as a practical way to instantiate a `GeneExpressionDataset` with in-memory data as well as for synthetic datasets, like those Pierre and Oscar have added.

Additionally, the `DownloadableDataset` could have as an `abstract_method` a `preprocess` method which would then have to be implemented in the children and could be safely called in the `__init__`.

Finally, for the `autotune` problem, I suggest we allow to pass either a loaded `GeneExpressionDataset` as we have now, which is safe 99% of the time.
Or, If ever the dataset exceeds 4Gb (this is humongous in sparse format), they can pass a `DownloadableDataset` sub-class in `gene_dataset_class` and  its arguments in `gene_dataset_kwargs` and if so `auto_tune_model_scvi` will only instantiate it inside the objective function.
Alternatively, for `DonwloadDataset`, we could implement a `load` method and a delayed_loading mechanism which allows `load` to be called after instantiation while keeping the default behaviour as it is today. 

As a side note, I would keep the preprocessing call as a default behaviour but would allow for it to be disabled by users who want to do things their way, I certainly would want that.

What do you think?

**Comment by jeff-regier** [comment]
For all the use cases I can think of the dataset is stored on disk, except for synthetic datasets.  Do you have other cases in mind? Even for testing our test data is stored on disk.

**Comment by jeff-regier** [comment]
I agree with your critiques of GeneExpressionDataset

**Comment by jeff-regier** [comment]
`DownloadableDataset` seems like a good abstraction. What methods does `CustomDataset` have that don't appear in `GeneExpressionDataset`? (Can we avoid having the extra class?)

**Comment by jeff-regier** [comment]
OK I'm open to doing away with all the dataset-specific subclasses. So up to you. I think whatever you come up with will be a big improvement.

**Comment by gabmis** [comment]
> OK I'm open to doing away with all the dataset-specific subclasses. So up to you. I think whatever you come up with will be a big improvement.

Ok, I'll suggest a PR asap. Thanks for the discussion.
