### ISSUE TITLE
clean up : remove commented out code

### ISSUE THREAD

**Issue by gabmis** [YosefLab/scVI#339]
Commented out code is bad practice in general, it makes the code less readable and can be quite confusing. In particular, class `GeneExpressionDataset` has a lot of it in methods `collate_fn_corrupted` and `corrupt`. `trainer` also has some in class `Trainer`, method `train`. There could be be some more, that's just what I saw until now.

**Comment by jeff-regier** [comment]
I also saw this gem while I was looking over the datasets, in the constructor of a subclass of `Dataset10X` called `BrainSmallDataset`:
https://github.com/YosefLab/scVI/blob/221cf0fe3b392f0b592aa8040dce4870a0dd908b/scvi/dataset/dataset10X.py#L189

Why would someone do that?

**Comment by gabmis** [comment]
Also wondering about these duplicate assignments in `CiteSeqDataset` :

https://github.com/YosefLab/scVI/blob/221cf0fe3b392f0b592aa8040dce4870a0dd908b/scvi/dataset/cite_seq.py#L44-L55

@jeff-regier do you know why this is done?

**Comment by jeff-regier** [comment]
It doesn't look like `self.adt_centered` is used anywhere so I think we can safely get rid of that assignment.

**Comment by gabmis** [comment]
I meant things like `self.adt = adt = pd.read_csv(...)`, why do we need `adt`, can't we just use `self.adt` ?

**Comment by jeff-regier** [comment]
Probably someone wanted to avoid having to type `self.` extra times. Not a good reason---more variables is more confusing than a few extra characters---but I bet that was the thinking.

Local variables, e.g. `adt`, are preferable to instance variables, e.g. `self.adt`, when either would work.

**Comment by gabmis** [comment]
> Local variables, e.g. adt, are preferable to instance variables, e.g. self.adt, when either would work.

Of course.

So these `= adt` should also be removed.

**Comment by jeff-regier** [comment]
Pierre removed th comments in #340

**Comment by gabmis** [comment]
Could we keep this open until all of the commented out code is gone? e.g in `trainer.py`
