### ISSUE TITLE
autotune : return STATUS_FAIL if nan in loss

### ISSUE THREAD

**Issue by gabmis** [YosefLab/scVI#346]

**Comment by jeff-regier** [comment]
Sounds like a good idea. 

Also, if you've found a setting of the hyperparameters that consistently generates NaNs, please do open an issue about that. I'll look into it then. We can usually avoid NaNs by making slight changes to the code, e.g. divide by 1e-8 rather than zero.

**Comment by gabmis** [comment]
Unfortunately, I was not able to trace back the NaNs. But, indeed, I've seen the loss go to NaN a few times since I've been working on scVI and it feels like it shouldn't happen and that there should be an easy fix for it.. will keep it mind..
