### ISSUE TITLE
Nonreproducible imputated data

### ISSUE THREAD

**Issue by jmbreda** [YosefLab/scVI#357]
Dear authors,

I'm willing to use the imputation function of scVI. I noticed that running the imputation tool twice on the same raw count table produced two unrelated results. I tried to rigorously follow the examples from the tutorial but I suppose I must be doing something wrong. Here is my small script: 

```
dataset = 'Baron'
in_file = 'Baron.csv.gz'
N_gene=False

from scvi.dataset import  CsvDataset
local_csv_dataset = CsvDataset(in_file,save_path='data/',compression='gzip',new_n_genes=N_gene)

import os
import numpy as np
import pandas as pd
from scvi.models import *
from scvi.inference import UnsupervisedTrainer
import torch

use_batches=False
use_cuda=True
vae = VAE(local_csv_dataset.nb_genes, n_batch=local_csv_dataset.n_batches * use_batches)
trainer = UnsupervisedTrainer(vae, local_csv_dataset, train_size=0.75, use_cuda=use_cuda)
full = trainer.create_posterior(trainer.model, local_csv_dataset, indices=np.arange(len(local_csv_dataset)))
imputed_values = full.sequential().imputation()

np.savetxt('data/' + dataset + '/scvi_count.txt',imputed_values.T,fmt='%.6e',delimiter='\t')
```

Thanks,
Jeremie Breda

**Comment by jeff-regier** [comment]
Hi Jeremie, Thanks for your interest in scVI! I believe you'd need to call `trainer.train()` somewhere in your code. Otherwise the model isn't fitted based on the data, and the imputed values would just be based on the random initialization. Please let me know if that solves the problem.

**Comment by jmbreda** [comment]
Hi Jeff, Yes, I added `trainer.train()` after creating `trainer` and before creating the posterior. It improves substantially the correlation between replicates. Thanks for your help!
