### ISSUE TITLE
Incorrect parameters in generate

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#360]
This should be px_scale instead of px_rate. See scVI preprint page 51.

https://github.com/YosefLab/scVI/blob/1cc8698aaa357f4a8dd12d2f49fbd21d8b29ef90/scvi/inference/posterior.py#L512

**Comment by romain-lopez** [comment]
correct

**Comment by adamgayoso** [comment]
I guess I was confused. I discussed with @PierreBoyeau and @oscarclivio.  The code actually outputs the right result. In scVI notation, the gamma represented in the code is actually `\ell w` which is a gamma with the same parameters but the scale is multiplied by `\ell`. This should be made clear with comments in the code, which I can add later.

**Comment by romain-lopez** [comment]
Oh I did not see that 

> X = np.random.poisson(l_train)

Yes you're right ! Thanks for adding those, it would be the same (the density calculations are in the paper). This density parametrization etc.. is not a clear point even in the manuscript so thanks for adding a comment in there, it really helps.

**Comment by romain-lopez** [comment]
should we close this issue @adamgayoso
