### ISSUE TITLE
unused variable in vae.py

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scVI#363]
Is this variable useless ?
https://github.com/YosefLab/scVI/blob/master/scvi/models/vae.py#L59

**Comment by jeff-regier** [comment]
This one seems useless too:
https://github.com/YosefLab/scVI/blob/05c1488d6f3b1e3ee3c984ac14e04d264ae9e280/scvi/models/scanvi.py#L63

It'd be good to delete both. These are the only two places where `n_latent_layers` appears in our codebase.
