### ISSUE TITLE
refactor VAE/LDVAE

### ISSUE THREAD

**Issue by gabmis** [YosefLab/scVI#377]
It would be nicer/cleaner to have only one VAE class, which allows to set the number of layers of the encoder and decoder separately (and have lists of hidden sizes instead of a single value). Additionally, a number of layers set to zero would mean a linear mapping - we could then get rid of the LDVAE class.

**Comment by adamgayoso** [comment]
I agree this would be nice. What do you think would handle 0 hidden layers? The model class or the modules classes (encoder, decoder)? It seems like the latter would be easier.

**Comment by jeff-regier** [comment]
The latter I think. There is still an encoder and a decoder if you have 0 hidden layers. They just have only weight matrix and one bias vector each.

**Comment by jeff-regier** [comment]
Merging VAE and LDVAE makes sense to me. @vals Are we overlooking anything?

**Comment by vals** [comment]
Sounds good to me!

This is basically how I prototyped the LDVAE, but for the implementation in the end I didn't want to change the API to the VAE for the sake of compatibility, so I sub-classed it. But if everyone is happy with this, it would be great, much cleaner, and people can experiment with asymmetric encoders/decoders.

**Comment by adamgayoso** [comment]
I'm closing this due to #497. I'm not sure it makes sense at the moment to go this route as it might make the core VAE class a bit bloated.
