### ISSUE TITLE
docs failing

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#378]
Our documentation build started failing about two weeks ago on readthedocs.io. Error message:
```
Searching for python-igraph>=0.7.1
Reading https://pypi.org/simple/python-igraph/
Downloading https://files.pythonhosted.org/packages/0f/a0/4e7134f803737aa6eebb4e5250565ace0e2599659e22be7f7eba520ff017/python-igraph-0.7.1.post6.tar.gz#sha256=a5ea42790a077eadb3d1e8f82edc47516fea4a2b26bbf52bfc148370fe0fe676
Best match: python-igraph 0.7.1.post6
Processing python-igraph-0.7.1.post6.tar.gz
Writing /tmp/easy_install-x9nn5yfc/python-igraph-0.7.1.post6/setup.cfg
Running python-igraph-0.7.1.post6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-x9nn5yfc/python-igraph-0.7.1.post6/egg-dist-tmp-iv798fpq
Cannot find the C core of igraph on this system using pkg-config.
We will now try to download and compile the C core from scratch.
Version number of the C core: 0.7.1.post6
We will also try: 0.7.1

error: Setup script exited with error: SandboxViolation: mkdir('/home/docs/checkouts/readthedocs.org/user_builds/scvi/checkouts/master/tmp', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

**Comment by romain-lopez** [comment]
Does the error come from python igraph then ?

**Comment by romain-lopez** [comment]
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] scvi.models                                            
generating indices... genindex py-modindex
highlighting module code... [100%] scvi.models.vaec                             
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 40 warnings.

The HTML pages are in docs_build.

**Comment by romain-lopez** [comment]
@jeff-regier can't reproduce the bug

**Comment by jeff-regier** [comment]
The red readthedocs badge on our project page still says docs failing though:
https://github.com/YosefLab/scVI

**Comment by jeff-regier** [comment]
See also
https://readthedocs.org/projects/scvi/builds/

**Comment by romain-lopez** [comment]
Yes I can see this problem in the build but I don't know how to work around that

**Comment by jeff-regier** [comment]
It may have something to do with what versions of our dependencies are getting installed at readthedocs.io when it builds our project, vs what you have locally on your machine. Does readthedocs.io install the versions in `requirements.txt`?

**Comment by romain-lopez** [comment]
hum does this sound helpful ?
https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by romain-lopez** [comment]
You can also look at the last build that passed, it looks like it managed to install the igraph before https://readthedocs.org/api/v2/build/9148991.txt

**Comment by jeff-regier** [comment]
Seems relevant. But did igraph just start depending on a C extension recently? Or did we just recently add the dependency on igraph?

**Comment by romain-lopez** [comment]
no, we compiled it in the last build so that's probably not it ?

**Comment by romain-lopez** [comment]
looks like it started failing after this commit 
https://github.com/YosefLab/scVI/commit/4eea43e2fefa559271a8c6b5f340611faa90bf7d

**Comment by romain-lopez** [comment]
but this commit did not touch the docstring so probably it does not come from there

**Comment by romain-lopez** [comment]
readthedocs relies on setup.py

**Comment by jeff-regier** [comment]
Some of the dependencies in setup.py probably shouldn't be in there. It may be easier to remove some of them than to figure out why they aren't working on readthedocs.io. I don't remember exactly why we rely on python-igraph, but if it's just used in one place that isn't part of many scvi users' workflows, then we could omit it, and log an error if that part of the code is reached and python-igraph isn't already installed. Something like
```
try:
    import igraph
except:
    logger.error("You must install python-igraph to call ....")
```

**Comment by romain-lopez** [comment]
should we put these two:
    "leidenalg>=0.7.0",
    "python-igraph>=0.7.1",

in extra then ?

**Comment by jeff-regier** [comment]
I think so

**Comment by coh-racng** [comment]
readthedocs link is not working ([https://scvi.readthedocs.io/en/stable/](https://scvi.readthedocs.io/en/stable/) ) Error message says the page does not exist yet.
