### ISSUE TITLE
Update posterior.generate() to reflect the model likelihood

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#379]
We should use `vae.reconstruction_loss` in the following function so that generate actually generates the correct data. Right now it is set to only generate NB data.

https://github.com/YosefLab/scVI/blob/31e87f4de0baeca85f39f5e510de2baf6af1efc7/scvi/inference/posterior.py#L508

**Comment by jeff-regier** [comment]
Seems like a problem. Where all is `generate` used? Could we delete this method entirely?

**Comment by adamgayoso** [comment]
@oscarclivio and @PierreBoyeau have used a modified version to generate NB and ZINB data. It seems like it would be a more generally useful method for posterior predictive checks if it actually used the correct distribution.

**Comment by romain-lopez** [comment]
@oscarclivio and @PierreBoyeau can presumably push their implementation in a PR ?

**Comment by adamgayoso** [comment]
We should also use PyTorch distributions instead of switching to cpu and using NumPy

**Comment by PierreBoyeau** [comment]
We are on it, i'll do a PR soon based on our branch
