### ISSUE TITLE
brain large : bug in gene subset selection

### ISSUE THREAD

**Issue by gabmis** [YosefLab/scVI#383]
https://github.com/YosefLab/scVI/blob/0830cd625e9de613074db14925905a653e778be5/scvi/dataset/brain_large.py#L67-L73

We are missing a call to transpose when selecting the most variable genes. Thus, we are effectively selecting the most variable cells and using their index to subselect genes.

**Comment by gabmis** [comment]
https://github.com/YosefLab/scVI/blob/0830cd625e9de613074db14925905a653e778be5/scvi/dataset/brain_large.py#L65-L66

And the data indices used to form the sample matrix for gene variance computation were in fact rna counts, probably copy/paste mistake.

**Comment by jeff-regier** [comment]
That's bad. For the hyperopt work, do you think you'd find that more layers are optimal if the bug were fixed?

**Comment by gabmis** [comment]
It's possible. A lot of genes carry a low amount of signal, e.g are almost all zeros, not knowing which we subsample can be problematic.
