### ISSUE TITLE
Numpy version is too old

### ISSUE THREAD

**Issue by ANazaret** [YosefLab/scVI#389]
Hey @jeff-regier , you limited Numpy version in #209 (https://github.com/YosefLab/scVI/blob/66cc63ead0d1a219f8d0ba1018d6f610f2b91679/setup.py#L13) but there are useful new functionalities in 1.15 and 1.16
We should require at least numpy 1.16 in `setup.py`

**Comment by jeff-regier** [comment]
Sure, that's fine. Versions later than 1.14 printed out a lot of warnings back when I put that limit on numpy, but perhaps that won't happen any more
