### ISSUE TITLE
Readthedocs versions

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#394]
Shouldn't read the docs by default show documentation for the last released version as opposed to the master branch? Or at least have the latest stable release docs available (right now would be 0.3.0)?

**Comment by adamgayoso** [comment]
Here is the relevant documentation https://docs.readthedocs.io/en/stable/versions.html

I looked into what scanpy does and they have a stable branch that seems to be a branch off master after a release.

**Comment by romain-lopez** [comment]
Solved on readthedocs
