### ISSUE TITLE
Error "Cannot convert CUDA tensor to numpy" and question about downsampling

### ISSUE THREAD

**Issue by Anguscgm** [YosefLab/scVI#398]
Dear Sir/Madam,

I am having an issue with the function sequential().get_latent(). I saw that #24 has nearly the same error message, but I am using a different function so I am not sure if it is the same case.

System information:
- CentOS Linux 7
- My device has GPU and CUDA available.
- I installed and ran everything under a conda environment

I am following "harmonization" under readme.
https://github.com/YosefLab/scVI/blob/master/tests/notebooks/harmonization.ipynb 
When I reach the step _latent, batch_indices, labels = full.sequential().get_latent()_ (under 
**Visualize the latent space**), I received the error "TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first."

I have attached the code I used for reference.
[scVI_trial.txt](https://github.com/YosefLab/scVI/files/3362441/scVI_trial.txt)

Besides, when I input the data, I find that for every csv, 10000 genes are downsampled to 600. And when I concatenate the CSVs into one data object, only 70 genes are kept. Is this normal behaviour?

Thank you very much.

**Comment by adamgayoso** [comment]
Hello,

Thanks for using scVI! I can try to address a few of your questions. 

First, the csv dataset has an option called `new_n_genes`.

https://github.com/YosefLab/scVI/blob/7df62412f9fa120182b06232075a2d257df09695/scvi/dataset/csv.py#L15.

By default it downsamples to 600 genes by variance. So this is being done for each dataset, and then when you concatenate them, they concatenate on gene names. Therefore, there are only 70 genes in the intersection of names across datasets. You may try not subsampling genes when loading each dataset and then subsample genes after concatenation.

As for the CUDA issue, I see that you save and load the model. Are you loading it on the same system?

**Comment by Anguscgm** [comment]
Thanks for the reply!

I see that's why the genes are downsampled! I will specify the `new_n_genes` when I use it later on.

For the save and load part, I copied it from the readme, but as it is a bit weird to save and load, I tried skipping it and run, but the same error still occurred.

I have updated the code used to clarify about the save and load.
[scVI_trial.txt](https://github.com/YosefLab/scVI/files/3364625/scVI_trial.txt)

I hope this can help solve the issue, please let me know if there is any more information I can provide.

Thank you!

**Comment by adamgayoso** [comment]
How did you install scVI?

**Comment by Anguscgm** [comment]
I install scVI in a conda environment with GPU available. My CUDA version is 10.0.

First I installed Pytorch.
`conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`

And then I installed scVI as in the readme.
`conda install scvi -c bioconda -c conda-forge`

Thank you!

**Comment by jeff-regier** [comment]
Your code in `scVI_trial.txt` looks fine. It's probably something about how pytorch/cuda is configured. What's the error message you get? (What line of scVI is indicated in the traceback?)

**Comment by jeff-regier** [comment]
Closed due to inactivity. Please open a new issue and include a traceback and we'll try to figure out what's happening!
