### ISSUE TITLE
h5 format from 10x_genomics

### ISSUE THREAD

**Issue by radio1988** [YosefLab/scVI#4]
For large datasets, e.g.  [1.3 million cells in mousr brain dataset](https://community.10xgenomics.com/t5/10x-Blog/Our-1-3-million-single-cell-dataset-is-ready-to-download/ba-p/276)

is there a support for [h5 format](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/h5_matrices)?

Thanks

**Comment by romain-lopez** [comment]
Hi, 

There is a TF version with this support from where the paper's results are derived. The code do no change much.

However, we are modifying the PyTorch version to natively handle all these formats. I suggest you look at the scVI-dev repo (which will be soon merged into scVI).

Thanks, 
Romain

**Comment by radio1988** [comment]
Thanks！

**Comment by jeff-regier** [comment]
@radio1988  We just posted a new version of scVI on the master branch that should make it straightforward to runs with the 1.3 million mouse cell dataset. You'd just run
```
./run_benchmarks.py --dataset brain_large
```
