### ISSUE TITLE
Automate running notebooks on full data to update outputs

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#400]
It looks like some of the notebooks have not been run in some time, or the outputs are out of date. How can we best make sure these are up to date?

The reproducibility notebook and harmonization notebook are good examples of this.

**Comment by romain-lopez** [comment]
All these notebooks should be in the unit tests so are run at every push on a PR ?

**Comment by jeff-regier** [comment]
The notebooks are run every time but the results in the notebooks aren't updated automatically. I think that's what Adam means.

On one hand, I don't think it's ideal to have notebooks in our main code repository. On the other hand, it's been working pretty well for us. We don't want to spend a lot of time developing a more complex workflow when what we have works pretty well.

Let's talk about this on Tuesday!

**Comment by gabmis** [comment]
Ideally, we'd want to automatically rerun the notebooks everytime a PR is merged in master but I don't see any easy-to-implement/non-painful way to do that. Coulb be part of our refactoring hackathon.

> On the other hand, it's been working pretty well for us.

They are a pain to debug..

**Comment by adamgayoso** [comment]
I'm changing this issue slightly - 

we should write a script that launches an EC2 instance, installs scVI, creates a new branch, runs the notebooks, sends a PR.

**Comment by adamgayoso** [comment]
This issue is more or less temporarily handled by running the notebooks through Colab and saving the output.
