### ISSUE TITLE
skip connections

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#401]
By introducing skip connections, we may be able to utilize deeper networks. We might start out with a resnet architecture, or a densenet.

The image below from [here](https://arxiv.org/pdf/1712.09913.pdf) illustrates how skip connections may simplify the loss function "landscape".

![skip](https://user-images.githubusercontent.com/8953355/60746854-3eabaf00-9f36-11e9-9eea-7f8d6d4bf4ef.png)

**Comment by adamgayoso** [comment]
This is actually in use in the totalVI decoder. I basically inject z at each layer in the decoder to keep it simple.

**Comment by jeff-regier** [comment]
I think a resnet architecture may work especially well.

**Comment by PierreBoyeau** [comment]
@romain-lopez @adamgayoso as discussed can we close this?

**Comment by romain-lopez** [comment]
closed
