### ISSUE TITLE
`benchmark.py` has commented code and unused function

### ISSUE THREAD

**Issue by ANazaret** [YosefLab/scVI#414]
@romain-lopez , @jeff-regier do you know why we still have these functions in the code-base?
https://github.com/YosefLab/scVI/blob/48740851f32e1bee8d4e87f3b18a2bec9ec97e9c/scvi/benchmark.py#L44-L51

Same,
https://github.com/YosefLab/scVI/blob/48740851f32e1bee8d4e87f3b18a2bec9ec97e9c/scvi/benchmark.py#L35-L41 
is never called in the code-base and I don't think either in the notebooks.

Thanks

**Comment by jeff-regier** [comment]
We probably don't need it any more. Would you delete it?

**Comment by ANazaret** [comment]
Yes I take care of that!

**Comment by jeff-regier** [comment]
Originally we weren't using jupyter notebooks in the code base and those benchmarks did everything. But people seemed to want notebooks. So now any code not called by one of the notebooks could probably be deleted

**Comment by jeff-regier** [comment]
Thanks!

**Comment by romain-lopez** [comment]
I would still keep the unit tests of course :)

**Comment by jeff-regier** [comment]
True, though some of our unit tests not in the notebooks are "smoke tests". We could probably delete those because all the code in the source directory should already be smoke tested by the notebooks.
