### ISSUE TITLE
Encoder architecture could be more efficient

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#417]
We should look into incorporating the library size parameters into the current `z_encoder`. This will increase the speed of training and in my tests could enable us to change the `log_variational` default. 

When I get a chance, I'll add a diagram of what architecture I was using.

**Comment by jeff-regier** [comment]
Or how about using a softmax as the first layer of `z_encoder`, so that its output is invariant to variations in library size?

**Comment by jeff-regier** [comment]
Seems like a good idea!

**Comment by adamgayoso** [comment]
I'm closing this issue as it's addressed in #477. It's in the codebase now, but I understand the apprehension to add it to the main vae.
