### ISSUE TITLE
Release a new scVI version

### ISSUE THREAD

**Issue by ANazaret** [YosefLab/scVI#421]
Here are the last steps before the next release:
- [x] autotune fixes
- [x] autotune notebook
- [ ] Update docs (when all is done)
- [ ] rerun all notebooks and commit them
- [ ] update bioconda

@gabmis edit if you think of anything else, thanks!

**Comment by jeff-regier** [comment]
@romain-lopez @gabmis Do we want release 0.4 as is? Or make other changes first?

**Comment by romain-lopez** [comment]
I'm not sure much is left to do !

**Comment by gabmis** [comment]
As is sounds good to me!

**Comment by romain-lopez** [comment]
I can run tox and push the new version. Let me know if there is anything special I should watch for. Will do that tomorrow.

**Comment by jeff-regier** [comment]
Sounds good, thanks Romain.

**Comment by romain-lopez** [comment]
done

**Comment by jeff-regier** [comment]
Is it released on bioconda?

**Comment by romain-lopez** [comment]
some problem with the build, I'll resolve that later today :)
