### ISSUE TITLE
Replace `inference` outputs 

### ISSUE THREAD

**Issue by PierreBoyeau** [YosefLab/scVI#422]
I think it could be helpful to replace the output of `inference` (which is currently a tuple) by a dictionnary.
That way it would be easier to use other models (that do not necessarily have the exact same outputs) with `Posterior`. It would maybe also help gain in clarity.
What do you think?

**Comment by gabmis** [comment]
@PierreBoyeau who's that question for? 
Seems like a good idea to me. :)
Will you submit a PR?

**Comment by PierreBoyeau** [comment]
To the community :house: !
Sure I'm on it
