### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'mongod': 'mongod'

### ISSUE THREAD

**Issue by zji90** [YosefLab/scVI#429]
I had the following error when running autotune.py
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "scvi/scVI-master/scvi/inference/autotune.py", line 358, in auto_tune_scvi_model
    multiple_hosts=multiple_hosts,
  File "scvi/scVI-master/scvi/inference/autotune.py", line 492, in _auto_tune_parallel
    stdout=mongo_logfile,
  File "/software/apps/python/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/software/apps/python/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mongod': 'mongod'

**Comment by ANazaret** [comment]
Hi, have you installed mongodb on your computer?

**Comment by romain-lopez** [comment]
If this is the problem, we might want to add this to the readme file of the repo :)

**Comment by tessadgreen** [comment]
Had the same error, fixed by running installing mongodb through conda (conda install -c anaconda mongodb). Thought at first that I needed to install MongoDB from their website but so far this seems to be working.

**Comment by zji90** [comment]
Thanks! I am using a computing cluster and it appears that mongodb is not installed. I have contacted the maintainer of the cluster and it seems that installing mongodb is not possible for now. Is there any workaround that I can still use the autotune function without mongodb (for example, some simple for loops to check whether parameter has the best cross validation performance)?

**Comment by gabmis** [comment]
Hi @zji90, thank you for your interest in scVI.
Unfortunately, the parallel autotuning process relies on mongodb for communication between the works and the trial generator. One workaround could be to try to patch these calls with calls to another service that you have installed. But, I am afraid that would take a lot of research/work.
I’d recommend you maybe insist on installing MongoDb on your machine :)
