### ISSUE TITLE
Travis spend 65% of test time on `pip install`

### ISSUE THREAD

**Issue by ANazaret** [YosefLab/scVI#434]
Most of the test time is lost on `pip install` which I believe spend 90% of the time building `leidenalg`, `python-igraph` and `louvain`.

It's not nice to wait that long to see a failing test that could be triggered in 1 minute.
Moreover these libraries are only use in notebooks, I'm not sure they are mandatory for the tests. We could just skip them in the notebook and keep the same coverage.

**Comment by adamgayoso** [comment]
I address this in #482. We can still tests notebooks on the side but I think I mostly fixed the issue.
