### ISSUE TITLE
Exploding library size after some iterations

### ISSUE THREAD

**Issue by PierreBoyeau** [YosefLab/scVI#441]
Hi all,

I spent a lot of yesterday figuring out what was wrong with one of my models, and thanks to @adamgayoso we found out it was linked to the library size.
Basically, during the first few iterations, the library size can take large values, making it easy for `px_rate` to be `inf` [here](https://github.com/YosefLab/scVI/blob/master/scvi/models/modules.py#L251), which can cause the reconstruction loss to be NaN.

I can do a PR that would clamp the library size just in case, and would also initialize the library encoder paramers so that libraries would be around 1 with a small variance at initialization.
What do you think?

**Comment by ANazaret** [comment]
Hey Pierre, it might be better for the records to talk about #446 here.

I'm glad that the `tanh/sigmoid` trick worked for you but I still don't know the exact change of behavior:
- `tanh` is like a smooth clamping so it seems good to me
- The `sigmoid` is also often used to get positive values but I'm not sure about the implications on the model of changing from `exp` to `sigmoid`

Happy if some people have good intuition on this.

**Comment by PierreBoyeau** [comment]
Closed based on last Tuesday's discussion
