### ISSUE TITLE
populate_from_data edits gene_names

### ISSUE THREAD

**Issue by coh-racng** [YosefLab/scVI#450]
While trying to debug why a DE gene found using scvi could not be found in the original anndata object, I realized that `GeneExpressionDataset.populate_from_data()` called by `AnnDatasetFromAnnData` would capitalize all the gene names. Just wanted make a note of this in case anyone else has this problem. It makes senes to make sure the gene_names are of `str` type. But it does not seem to be necessary and can be confusing to capitalize gene_names in the backend, when the user provides the dataset with given gene names. 

``` python
        if gene_names is not None:
            self.initialize_gene_attribute(
                "gene_names", np.char.upper(np.asarray(gene_names, dtype="<U64"))
            )
```

**Comment by romain-lopez** [comment]
Hi, 

I believe we use this in order to match the names more easily across multiple datasets.

What do you think would be a better option ?

Romain

**Comment by fbrundu** [comment]
Hi @romain-lopez , what's the use case that you're solving by capitalizing names?
Matching datasets of different organisms? In that case you can convert names to unique orthologs in one target organisms.
I also disagree with use of capitalization in this case because it creates confusion regarding the dataset's organism. In my opinion it should be optional, and turned off by default.

**Comment by romain-lopez** [comment]
Hi, the idea for this is simply to facilitate merging different datasets when some gene names are capitalized and some others are not. I agree that we might want a more user-friendly API giving the option to capitalize or not. 

Do you have other suggestions @fbrundu ?

**Comment by adamgayoso** [comment]
I think we should leave it to the user to compare gene names when merging datasets, so it's best not to alter their gene names behind the scenes. 

Perhaps it's a bit more work for users in some cases, but they can manually make both their datasets have upper gene names in two commands.
