### ISSUE TITLE
mongodb required for unit tests

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#451]
If I follow the installation instructions for scvi exactly, but don't install mongodb, which is listed as optional, the unit tests don't pass:
```
ERROR    scvi.inference.autotune.all:autotune.py:150 Caught (2, "No such file or directory: 'mongod'") in auto_tune_scvi_model, starting cleanup.
Traceback (most recent call last):
  File "/home/regier/scVI/scvi/inference/autotune.py", line 144, in decorated
    return func(*args, **kwargs)
  File "/home/regier/scVI/scvi/inference/autotune.py", line 428, in auto_tune_scvi_model
    multiple_hosts=multiple_hosts,
  File "/home/regier/scVI/scvi/inference/autotune.py", line 574, in _auto_tune_parallel
    stdout=mongo_logfile,
  File "/home/regier/miniconda3/envs/testscvi41/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/regier/miniconda3/envs/testscvi41/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```

@romain-lopez @gabmis 
Should we have added `mongodb` to requirements, and to the meta.yml file uploaded to bioconda?

**Comment by jeff-regier** [comment]
If I manually instal `mongodb`, I get this error:
```
>   ???
E   ModuleNotFoundError: No module named 'scanpy'
```

It seems like the dependencies need to be updated.

**Comment by jeff-regier** [comment]
After installing those two packages:
```
>   from colour import Color
E   ModuleNotFoundError: No module named 'colour'
```

I think we'd want conda to automatically install all these dependencies so that scVI works right away for users.

**Comment by gabmis** [comment]
@jeff-regier These are all test dependencies so I’m not sure we want them installed for users. On the other hand, for contributors, if it’s not the case, CONTRIBUTING.rst should make it clear that MongoDb is required.

**Comment by jeff-regier** [comment]
Are some of the other packages that conda already installs also purely test dependencies? See
https://github.com/bioconda/bioconda-recipes/blob/2ee08b33c4347248e86fc5ba3232577cf04d729b/recipes/scvi/meta.yaml#L22-L42

Seems like we should be consistent -- either install all the test dependencies automatically or not.

I'd lean towards installing as many as we can, so that users aren't frustrated by error messages. But I'm not entirely sure what standard practice is. Maybe it matters that are users are all developers, effectively.

**Comment by gabmis** [comment]
leidenalg and python-igraph definitely are test dependencies (for some notebook). We would have to check the rest against our requirements.txt file.
IMO, the people that run unit tests, ie contributors, will fork the repo so no need to to install dependencies when using conda.
And, for users wanting to use our notebooks, the notebook should explicitly mention their dependencies (in
bold, at the top of the notebook).
Especially more so since the leidenalg and igraph dependency take minutes to install..

**Comment by jeff-regier** [comment]
We could list these test dependencies in the "test requirements" section:
https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#test-requirements

**Comment by jeff-regier** [comment]
Very few of the packages conda currently installs along with scVI are strictly required to use parts of scVI. All the following are installed now:
```
    - pytest-runner >=4.0
    - python >=3.6
    - pip >=19.0
    - numpy >=1.16
    - matplotlib >=3.0
    - scikit-learn >=0.20
    - scipy >=1.2
    - h5py >=2.9
    - pandas >=0.24
    - loompy >=2.0.17
    - tqdm >=4
    - anndata >=0.6
    - xlrd >=1.2
    - jupyter >=1.0.0
    - nbconvert >=5.5.0
    - nbformat >=4.4.0
    - ipython >=7.5
    - umap-learn >=0.3.7
    - seaborn >=0.9.0
    - leidenalg >=0.7.0
    - python-igraph >=0.7.1
```

Do we want to remove most of these then, rather than adding `mongodb`, `colour`, `scanpy`, and `pymongo`?

**Comment by romain-lopez** [comment]
Refer to #452. 
1. I think MongoDB is definitely necessary to pass the unit tests and has to be installed via the system (not pip or conda).
2. Regarding the rest, can we merge these dependencies with just setup.py ?

**Comment by gabmis** [comment]
@romain-lopez just the install dependencies (not the test), right?

**Comment by jeff-regier** [comment]
I add the missing test dependencies to our conda meta.yml file. In the future, we may want to remove all the test dependencies from conda, but for the time being it seemed better to have all of them there rather than just some of them.
