### ISSUE TITLE
`data_loading` tutorial notebook missing path to `TM_droplet_mat.h5ad`

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scVI#463]
Minor thing: 
When running the tutorial `data_loading notebook`  it couldn't find the dataset `TM_droplet_mat.h5ad`. I solved that by adding a new cell telling it to first download the dataset from the github repo, and then loading it as normal.

```
remote_ann_dataset = DownloadableAnnDataset(
    "TM_droplet_mat.h5ad", 
    save_path=save_path, 
    url='https://github.com/YosefLab/scVI/blob/master/tests/data/TM_droplet_mat.h5ad?raw=true'
)
```
There are the cells in the notebook:
https://github.com/YosefLab/scVI/blob/5fe194d4c30d7a07fa1a4b0a65e057a43262d5de/tests/notebooks/data_loading.ipynb#L200-L231

**Comment by adamgayoso** [comment]
Thanks for pointing this out. I believe this was actually intended to show how to load a local Anndata dataset, which may also be done by using the DownloadableAnndataset class. We will clear this up and refresh the tutorials.
