### ISSUE TITLE
Testing notebooks only as side tests

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scVI#466]
Hi, 

Here are a few remarks about the testing issues of the codebase. @jeff-regier @adamgayoso what do you think ?

** TESTING **

We are having all the requirements and testing issues mostly because we rely on UMAP, igraph, scanpy etc.. for unit tests while I believe that only the codebase should be tested. This is especially problematic since the unit tests by travis need even to compile igraph etc... which honestly does not make much sense.

Still, trying out the notebooks is important to make sure our API is still compatible with scanpy and other software and that a wide range of people will run the tutorial without any trouble. 

Hence, here is an idea. How about having two different testing platforms, composed of:
+ unit tests
+ notebook tests

Only the unit tests are necessary to merge a branch to master. However, the notebook tests are still run on the background for each PR and there is simply a badge on the readme that indicates whether notebook tests pass or fail (as it is the case for the docs for example). 

When notebook fail, this will be the job of the maintainer to update things but at least for quick developments we will not run into these issues. 

** VERSION **

About the version system, it looks like the unit test would from now on only need the only strictly necessary packages to be installed while the notebook tests (background) would need to install extras. 

Consequently, it seems reasonable to have a requirements.txt file that has ONLY the necessary files to run the unit tests and NOT the notebooks.

setup.py will parse requirements.txt and have all the extras requirements to run the notebooks.

conda should either use setup.py or also install the extras. 

** README **

The readme should make it clear that the extras are needed to run the notebook examples. Also, it should make it clear that MongoDB is necessary whenever hyperopt is used.

**Comment by romain-lopez** [comment]
@PierreBoyeau

**Comment by PierreBoyeau** [comment]
It sounds good to me, I can take care of that!

**Comment by jeff-regier** [comment]
Seems fine

**Comment by romain-lopez** [comment]
great ! please refer to #434 #451 and #452 ! This should close all of them !

**Comment by romain-lopez** [comment]
@PierreBoyeau anything new on this problem ? What is left to do in order to close this ?

**Comment by PierreBoyeau** [comment]
Hi,
Sorry I have been pretty busy. So far here is what is done:
- removed requirements
- installing scVI without dependencies as default using pip or in local. For instance
`pip install scvi` would install scVI without its dependencies whereas `pip install scvi[notebooks]` would install everything if I got this right
- fix sklearn issue with new versions
- increased coverage (wip)
- I still don't know if we can get a custom badge, but I am working on an alternative, I will keep in touch

What remains to do:
- numba behavior in version .45.1 causing build to fail
- bioconda update

**Comment by romain-lopez** [comment]
Ok great ! 

After this, we will also need to:
- Add some comments to the README file to make sure the different commands for installing scVI are clear (with extras and without extras) and explain the same for bioconda.

**Comment by romain-lopez** [comment]
this will not be necessary anymore
