### ISSUE TITLE
Question about annotating using other datasets

### ISSUE THREAD

**Issue by kawairine** [YosefLab/scVI#472]
Hi,

I was wondering what can be a good approach for annotating a dataset from two other datasets? It is because cell types between the reference datasets are not overlapping, and I wonder if I simply use them as the labelled set, will scANVI assume they are from the same distribution? 

And if i only take a subset of the reference dataset for making the model, shall I take the mean and variance of the whole dataset, or mean and variance of the selected subset of the dataset?

Many Thanks!

**Comment by romain-lopez** [comment]
Hi, 

I am not sure I completely understand some of your questions. Let me try to answer you.

> I was wondering what can be a good approach for annotating a dataset from two other datasets? It is because cell types between the reference datasets are not overlapping, and I wonder if I simply use them as the labelled set, will scANVI assume they are from the same distribution?

In this setting, scANVI will indeed tend to predict cell types that it was trained on. So if there are novel cell types in the unannotated dataset it can become a problem. To mitigate this effect, we advise to visualize the local batch entropy alongside with the prediction. For example, scANVI's cell type predictions might be erroneous for cell which did not mix at all with the annotated set.

> And if i only take a subset of the reference dataset for making the model, shall I take the mean and variance of the whole dataset, or mean and variance of the selected subset of the dataset?

To which mean and variance are you referring to ?

Romain

**Comment by kawairine** [comment]
Hi, 

Thank you for the prompt response. 

> Hi,
> 
> I am not sure I completely understand some of your questions. Let me try to answer you.
> 
> > I was wondering what can be a good approach for annotating a dataset from two other datasets? It is because cell types between the reference datasets are not overlapping, and I wonder if I simply use them as the labelled set, will scANVI assume they are from the same distribution?
> 
> In this setting, scANVI will indeed tend to predict cell types that it was trained on. So if there are novel cell types in the unannotated dataset it can become a problem. To mitigate this effect, we advise to visualize the local batch entropy alongside with the prediction. For example, scANVI's cell type predictions might be erroneous for cell which did not mix at all with the annotated set.
> 
> > And if i only take a subset of the reference dataset for making the model, shall I take the mean and variance of the whole dataset, or mean and variance of the selected subset of the dataset?
> 
> To which mean and variance are you referring to ?

Sorry, let me elaborate more. I wanted to build a classifier from two reference dataset, that the cell types are not overlapped. Since now the labelled set is from two different dataset, will it be problematic, will scANVI assume they are from same distribution?  

And another not related question is that if I want to take a subset of a dataset ( only interested in certain cell types), Do I take the mean and variance
I was referring to when a GeneExpressionDataset() was created, the library size is automatically calculated. So I was wondering what will be a better approach for measuring the local_mean and lcoal_var for the subset. Before the subsetting, or after subsetting? 

Thank you!

**Comment by romain-lopez** [comment]
> Sorry, let me elaborate more. I wanted to build a classifier from two reference dataset, that the cell types are not overlapped. Since now the labelled set is from two different dataset, will it be problematic, will scANVI assume they are from same distribution?

As long as you mention the right covariates for batches (0, 1, and 2) then you should not run into problems. 

> And another not related question is that if I want to take a subset of a dataset ( only interested in certain cell types), Do I take the mean and variance
I was referring to when a GeneExpressionDataset() was created, the library size is automatically calculated. So I was wondering what will be a better approach for measuring the local_mean and lcoal_var for the subset. Before the subsetting, or after subsetting?

Better is probably after subsetting.

**Comment by kawairine** [comment]
> > Sorry, let me elaborate more. I wanted to build a classifier from two reference dataset, that the cell types are not overlapped. Since now the labelled set is from two different dataset, will it be problematic, will scANVI assume they are from same distribution?
> 
> As long as you mention the right covariates for batches (0, 1, and 2) then you should not run into problems.
> 
> > And another not related question is that if I want to take a subset of a dataset ( only interested in certain cell types), Do I take the mean and variance
> > I was referring to when a GeneExpressionDataset() was created, the library size is automatically calculated. So I was wondering what will be a better approach for measuring the local_mean and lcoal_var for the subset. Before the subsetting, or after subsetting?
> 
> Better is probably after subsetting.

Hi,

I would like to understand more about the logic for taking local_mean and local_var after the subsetting. Will the mean and var be over-or under-estimated  if we take them after subsetting, as other cells from the same library are not considered in the calculation?

Thanks!

**Comment by romain-lopez** [comment]
We set the prior based on the empirical mean and variance of the log-library size. I guess if you subsample the data you want to change these to reflect the changes. It is possible that it does not really matter for downstream analysis. 

Hope that helps, 
Romain
