### ISSUE TITLE
'GeneExpressionDataset' has no attribute 'get_attributes_from_matrix'

### ISSUE THREAD

**Issue by royoelen** [YosefLab/scVI#474]
I am trying to run through your notebook "https://github.com/YosefLab/scVI/blob/master/tests/notebooks/linear_decoder.ipynb", and am encountering the error "'GeneExpressionDataset' has no attribute 'get_attributes_from_matrix'" when trying to run the step "X, local_means, local_vars, batch_indices, labels = GeneExpressionDataset.get_attributes_from_matrix(adata.X)"

Has this function been deprecated and removed in favour of another one or am I doing something wrong here?

I am using a virtual environment with Anaconda, and cloned and installed this project using the setup.py included in the repo.

**Comment by romain-lopez** [comment]
Yes, indeed this linear_decoder notebook is the only one that is not unit tested and we changed the API in the last versions of scVI. We need to update this notebook. I suggest you to look at the data_loading notebook for hint how to modify this line.

**Comment by jszym** [comment]
FWIW, Linear Decoder is not the only notebook out of date. The [harmonization ](https://github.com/YosefLab/scVI/blob/master/tests/notebooks/harmonization.ipynb) notebook has the same issue with `GeneExpressionDataset` , and the [data loading](https://github.com/YosefLab/scVI/blob/master/tests/notebooks/data_loading.ipynb) notebook makes use of `DownloadableAnnDataset`  (which I think might be `AnnDataset` now).

Perhaps you might point us to the version of scVI that these notebooks were written for? That would be a huge help.

**Comment by adamgayoso** [comment]
We will be addressing this issue in a new release (hopefully next week). Thank you for your patience.

**Comment by romain-lopez** [comment]
How come we have these issues with the harmonization notebook ? I just checked and it is supposed to be unit tested ?

**Comment by adamgayoso** [comment]
@romain-lopez how do you want to handle the linear decoder notebook? If we don't plan on testing that notebook we should add a cell in there saying that and pointing to our data loading tutorial and close this issue, or fix the code.

**Comment by romain-lopez** [comment]
So, I looked into it and it seems like both of the linear decoder notebook and the scanpy notebook rely on the same dataset (pbmc3k). Because of that, it means it should be quite easy to unit test this notebook (it was to me the major pain point before):
+ use the unit test data from the scanpy notebook
+ Change GeneExpressionDataset.get_attributes_from_matrix by the new anndata loader class

**Comment by romain-lopez** [comment]
so we might as well do that
