### ISSUE TITLE
add AnnData support

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#48]
Let's support reading from AnnData files.

https://github.com/theislab/anndata/issues/30#issuecomment-398677211

**Comment by imyiningliu** [comment]
I think `anndata` has methods that read `csv`, `h5ad`, etc. files and returns a `AnnData` object. Do initialize `AnnDataset` with `AnnData` object (not `url`)?

**Comment by jeff-regier** [comment]
Probably best to get it working for the one concrete example we have:
https://s3.amazonaws.com/czbiohub-tabula-muris/TabulaMuris.h5ad.zip

You might change run_benchmarks so the following works:
```
./run_benchmarks.py --anndata TabulaMuris.h5ad
```

**Comment by imyiningliu** [comment]
After I download the above lint, it's a folder that has two `.h5ad` files. Is that okay if i added an extra parameter to indicate which file to read?

**Comment by jeff-regier** [comment]
I thought AnnData files were supposed to have all the data we need in just one file. Why are there two files then? Can we ignore one of the two?

**Comment by imyiningliu** [comment]
There're two files in the folder: `TM_droplet_metadata.h5ad` and `TM_facs_metadata.h5ad`, which matches with [this](https://github.com/czi-hca-comp-tools/easy-data/blob/master/datasets/tabula_muris.md). I've pushed the code with including an extra parameter when downloading a folder.

**Comment by jeff-regier** [comment]
Can we make it so it works for *either* of these two h5ad files, but not both at once?

**Comment by jeff-regier** [comment]
```
./run_benchmarks.py --dataset TM_droplet_metadata.h5ad
```
