### ISSUE TITLE
How to summary output of VAE

### ISSUE THREAD

**Issue by grasscliff** [YosefLab/scVI#483]
Hello,

Thank you for this software for scRNAseq. Now I'm wondering, is there any detailed description of the output object of VAE?

Particularly,
I'd like to know if the output includes the estimated dispersion values and/or expected dropout rate? If yes, what special parameter should I set and what command can I use to extract them?

Thank you very much!

**Comment by adamgayoso** [comment]
You can extract the dispersion with `vae.px_r`, note this is on the natural log scale.

For dropout, you can get the dropout probability given a sample of z using `posterior.generate_parameters`. You should inspect the function yourself, the first return value is the tensor you want. Keep in mind this is per gene and per cell.

**Comment by grasscliff** [comment]
It works. Thank you very much!
