### ISSUE TITLE
Documentation of local 10x loading

### ISSUE THREAD

**Issue by allonw** [YosefLab/scVI#486]
It seems to me that the documentation of the Dataset10X function revolves around the use case of downloading one of the pre-defined datasets, and it's not at all clear that this is also the function to use for reading a new user-generated 10x data (presumably a more common scenario). 

Unless I missed something in the docs, I had to look in the code to realize this was the right function to use and what path it was expecting

**Comment by adamgayoso** [comment]
Hi @allonw, thanks for pointing this out. We have a PR up for a new data loading tutorial, but I think this should be made even more explicit in the tutorial exactly what directory structure is expected.
