### ISSUE TITLE
Refactoring the differential expression module

### ISSUE THREAD

**Issue by PierreBoyeau** [YosefLab/scVI#487]
I did a WIP PR for the LFC/DE estimation based on current code (my code looked nothing like that)
More precisely I simplified (I hope) the codebase for DE generally speaking. I will take care of IAF later on (which will require carefulness to as it optimizes another formulation of the ELBO) and I added two very simple functions:
- `estimate_change` computes the posterior properties of the change variable (LFC or used specified)
- `estimate_de_probability` computes the probability of being DE with our LFC formulation with threshold \delta.

As a reminder, the core function based on Bayes factors is in `differential_expression_score`. I did not touch that method, except to refactor it slightly. I am pretty sure a lot can be done/changed/simplified but I just wanted to get your opinion right now on several points.

1. While `all_stats` used by the BF version makes sense to me (it is nice to provide side informations on genes in addition to de scores), I am not sure the `bayes1_permuted` `bayes2` `bayes2_permuted` scores are really useful and I think we could get rid of those.
2. `differential_expression_score` and `estimate_de_probability` should somehow be merged. A complication is that outputs will potentially be different. Maybe returning a pandas DataFrame all the time could be a solution?
3. I was also wondering about the following thing: currently we sample `n_sample` times from the aggregated posterior. While I like this formulation (because it is quite staightforward), I used in the code for my article something similar to `n_samples_per_cell` argument of modified function `sample_scale_from_batch`. I don't know if this parameter makes sense, but if we don't include it I think all de related methods should inform the user of the number of time each cell posterior is sampled from for instance, and warn him if it is not sampled from enough
4. I think we could move all functions in the end of `posterior.py` (which are not `Posterior` methods) in another file (`posterior_utils.py` ?) for clarity. What do you think?
Anyway, I just wanted to ping you about the WIP PR and get your point of view on what straightforward modifications/simplifications we should do for the DE part of scVI

**Comment by adamgayoso** [comment]
I think this is starting to look really good. It looks like all the code is in place.

> While all_stats used by the BF version makes sense to me (it is nice to provide side informations on genes in addition to de scores), I am not sure the bayes1_permuted bayes2 bayes2_permuted scores are really useful and I think we could get rid of those.

They are not useful in my opinion.

> While I like this formulation (because it is quite staightforward), I used in the code for my article something similar to n_samples_per_cell argument of modified function sample_scale_from_batch.

It is certainly more straightforward to know how many times your cells were sampled versus how many times your subpopulation was sampled.

As for how we should implement this:

I think we can take advantage of some abstraction by using a new differential expression class.

The class takes as input 4 things:
1) Posterior object 
2) Function name of posterior method to get values you want to use for DE (px_scale in this case, specific function is `get_harmonized_scale()`)
3) Function you will use to compare values (lfc, p_a > p_b)
4) Decision boundary

with this new class we could just move the functions you already wrote and clean up the current posterior. Also, the method in 2) must have the option to integrate over batches.

Then I think the posterior would have a new method called `get_bayes_factors()` that instantiates the differential expression class with the correct initialization and runs DE.

This would be very helpful for new models we add to the repo as new posteriors can use different model values to do DE with and override `get_bayes_factors()` with their own specification.
