### ISSUE TITLE
logging should be done on stdout and not stderr

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scVI#503]
We need to make sure this wasn't done by Gabriel for something specific linked with autotune multiprocessing.

**Comment by adamgayoso** [comment]
I believe all we need to do is change this line

https://github.com/YosefLab/scVI/blob/772f69ebfae93af9c0afa75cced764501eee6c85/scvi/_settings.py#L55

to

`ch = logging.StreamHandler(sys.stdout)`

In addition, we should make

https://github.com/YosefLab/scVI/blob/d839c550641df03f53f37f8051836f4ceb575445/scvi/_settings.py#L63

a debug statement so it does not appear every time you import scvi.
