### ISSUE TITLE
redundant posterior function

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#506]
It's not clear this function does anything that `get_latent` doesn't do. It's also poorly named

https://github.com/YosefLab/scVI/blob/d839c550641df03f53f37f8051836f4ceb575445/scvi/inference/posterior.py#L723

**Comment by PierreBoyeau** [comment]
Maybe we could get rid of this method by merging all the `Posterior`'s getters that have the structure:
```
        some_variables = []
        for tensors in self:
            sample_batch, _, _, batch_index, labels = tensors
            vars = self.model.inference(x, batch_index, y)[some_key(s)]
            some_variables += [np.array(vars.cpu())]
        some_variables = np.concatenate(some_variables)
        return some_variables
```

in a unified getter? What do you think of implementing a `__getitem__` to do so?

**Comment by adamgayoso** [comment]
I think this could be nice, but maybe also lumped into this issue is the level of abstraction of our classes. For example, in `total_inference.py` I had to rewrite the imputation list function just so the protein data is loaded properly, all other code is identical. I think this would be fixed with your get item suggestion but then we have to ensure the keys are consistent across models.

**Comment by adamgayoso** [comment]
Closing this as it is no longer relevant as of #723
