### ISSUE TITLE
Subsample_cells doesn't really subsample

### ISSUE THREAD

**Issue by ANazaret** [YosefLab/scVI#508]
How do you feel about the function `subsample_cells`? It doesn't subsample randomly. It just keeps the cells with the highest number of total gene counts.

https://github.com/YosefLab/scVI/blob/d839c550641df03f53f37f8051836f4ceb575445/scvi/dataset/dataset.py#L970-L985

**Comment by adamgayoso** [comment]
I'm not sure how this function is exactly useful. My vote is to remove it.

**Comment by adamgayoso** [comment]
Closing due to dataset refactor.
