### ISSUE TITLE
terminate training if nan elbo

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#511]
we should terminate the training loop if the model has nan train loss and/or test loss for M consecutive iterations.

**Comment by PierreBoyeau** [comment]
That would imply saving the train elbo in `history` no matter the value of `frequency` right?
I agree that this is a needed feature. We should also raise a warning whenever a NaN pops up

**Comment by adamgayoso** [comment]
actually yeah a warning if a NaN pops up (every time it does) should be sufficient because then the user can just stop the training. But ideally, this sort of automated nan stopping would reduce computation time, money, energy, etc.
