### ISSUE TITLE
Library size is miscomputed

### ISSUE THREAD

**Issue by ANazaret** [YosefLab/scVI#524]
Somehow in `populate_from_datasets` the order of operations is such that the batch library size computation is not called properly.
https://github.com/YosefLab/scVI/blob/2dac5d524fd89a2344df024897ebf83296d627e4/scvi/dataset/dataset.py#L272

Function `.compute_library_size_batch()` should be called at the end.

**Comment by adamgayoso** [comment]
I'm not sure I see what the issue is? If the library sizes are concatenated it should be fine, no?

I see that the computation first computed here:
https://github.com/YosefLab/scVI/blob/2dac5d524fd89a2344df024897ebf83296d627e4/scvi/dataset/dataset.py#L342

but then gets overwritten later?

Could you submit a PR if it's really an issue?

**Comment by ANazaret** [comment]
I didn't investigate why there was a bug but when I call the function it sets to 0 the library size of the second dataset. My fix was to call again the function (I did it in my local code). It might be worth trying to understand what is going wrong.

**Comment by adamgayoso** [comment]
This is very weird as I don't seem to have the issue. It seems like we can exclude the local means and local vars from the for loop over cell attributes to keep and the redundancy would be resolved, since it gets calculated in the line I sent above.

**Comment by adamgayoso** [comment]
Were you able to figure out if this is actually a bug, @ANazaret?

**Comment by ANazaret** [comment]
Hey @adamgayoso. So I looked at the code and different things: indeed removing "local_means" and "local_vars" seems coherent (it actually fixed the unexplained 0 that I had). However, it doesn't solve entirely the problem because `populate_from_data` doesn't have access to the batch indices yet. They will only be merged later, so the mean is the same for the whole dataset.

Thus I believe calling `.compute_library_size_batch()` at the end will make sure the library size is well computed!
