### ISSUE TITLE
sklearn bug

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/scVI#528]
We have some issue with sklearn when modifying the readme. That should come from something deprecated from our code ?

https://travis-ci.org/YosefLab/scVI/builds/620632239

@PierreBoyeau would you look into that and try to:
+ merge the README modif
+ fix the codecov and make sure the new PR get a codecov
+ merge the posterior predictive checks
+ merge the gene filtering fix

**Comment by PierreBoyeau** [comment]
You're right, I am pretty sure it's linked with the new sklearn [update](https://scikit-learn.org/stable/whats_new/v0.22.html). I'm on it!
