### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by teddygroves** [YosefLab/scVI#530]
Hi there!

I tried cloning the repository and installing locally in a fresh python 3.7.2 virtual environment and ran into a few problems. First when I tried `python setup.py install` I hit the following error:

```
error: prompt-toolkit 3.0.2 is installed but prompt-toolkit<2.1.0,>=2.0.0 is required by {'jupyter-console'}
```

Next I tried running `pip install -e .` from the root directory. This worked, but I had to install the package `anndata`. I think this package should perhaps be added to the requirements in `setup.py`.

**Comment by adamgayoso** [comment]
Yes thank you for pointing this out, `anndata` should be in the setup.py main requirements.

For now, you could also install using `pip install .[notebooks]`
