### ISSUE TITLE
access the scvi.dataset.loom.LoomDataset object

### ISSUE THREAD

**Issue by pchiang5** [YosefLab/scVI#534]
Hello,

I have loaded a loom object from with the XXX = LoomDataset() function.

When I type XXX, the following information showed:
<scvi.dataset.loom.LoomDataset object at 0x0000018368C8D408>

Is there any tutorial about how to access and change the names of the object (such as metadata, row and column names)? 

Thank you

**Comment by adamgayoso** [comment]
Hello,

I recommend you check out our [data loading tutorial ](https://nbviewer.jupyter.org/github/YosefLab/scVI/blob/master/tests/notebooks/data_loading.ipynb)

It's not clear from your issue what exactly you'd like to do, but the `XXX` object is not a Loom dataset object, it's an scVI `GeneExpressionDataset` object where attributes were populated from a loom file.
