### ISSUE TITLE
Training in Introduction to scVI

### ISSUE THREAD

**Issue by ethankinchan** [YosefLab/scVI#554]
hi,senior.I found that the code ran with the following error:
Traceback (most recent call last):
  File "DataLoading.py", line 22, in <module>
    gene_dataset = CortexDataset(save_path=save_path, total_genes=558)
  File "/home/admin301/anaconda3/envs/pytorch/lib/python3.7/site-packages/scvi/dataset/cortex.py", line 50, in __init__
    delayed_populating=delayed_populating,
  File "/home/admin301/anaconda3/envs/pytorch/lib/python3.7/site-packages/scvi/dataset/dataset.py", line 1346, in __init__
    self.populate()
  File "/home/admin301/anaconda3/envs/pytorch/lib/python3.7/site-packages/scvi/dataset/cortex.py", line 69, in populate
    X = np.asarray(rows, dtype=np.int).T[1:]
  File "/home/admin301/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
and i don't know how to solve it?

**Comment by adamgayoso** [comment]
Hello,

I would ensure the `save_path` is correct. If you're running the tutorial notebook please ensure that the working directory of the notebooks is the same directory that the notebook is in.

**Comment by ethankinchan** [comment]
I'm very thanks for your reply.At first,the file "DataLoading.py" is under the directory of "/home/admin301/chenjian/scVI/"(D1),and then i move it to the path as "/home/admin301/chenjian/scVI/data/"(D2) and it ran successfully and output a folder called data.(about data,the former is from the "Data Loading Tutorial",the later is in this tutorial).I was puzzled by a question here that I ran the "Data Loading Tutorial" in the directory of D1 and ran the "Training" of basic usage in D2 and both worked.so why the "Training" couldn't work in D1?whether these two tutorials are independent of each other?

**Comment by adamgayoso** [comment]
I am not clear as to what you mean by `DataLoading.py`. This is not a file in our repository. Loading dataset objects depends on the save path in many instances, so ensuring that the save path is correct is critical.

**Comment by ethankinchan** [comment]
the file "DataLoading.py" include codes of Loading the data&Training the model.I didn't use jupyter but pytorch to ran these codes
