### ISSUE TITLE
Potential issue in DE when using a Posterior that does not include entire dataset

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#557]
It's hard for me to tell if this is a bug. If I make a Posterior object on some subset of cells, shouldn't the following lines be in reference to the indices I already am using in the Posterior?

https://github.com/YosefLab/scVI/blob/6c9f43e3332e728831b174c1c1f0c9127b77cba0/scvi/inference/posterior.py#L379-L385

**Comment by romain-lopez** [comment]
it looks like this is by default collecting all cells from the dataset then
? That sounds like an ill-behavior. By default this should return only
normalized values for the already selected cells ?

Romain
-----------------------
Romain Lopez
PhD candidate, EECS
UC Berkeley
romain_lopez@berkeley.edu
+1 (650) 422 9703

**Comment by adamgayoso** [comment]
Not exactly, it updates the indices the posterior uses to sample cells based on the selection. This assumes the selection is done with respect to the whole dataset.

So we'd have to be clear that DE must be done with respect to the "full_posterior" or update this function.

**Comment by adamgayoso** [comment]
Ok so yeah DE is done only on full posteriors - we should add info statements to make that clear.

**Comment by romain-lopez** [comment]
That sounds like a good idea.
