### ISSUE TITLE
add umap embedding and cluster numbers back to loom files

### ISSUE THREAD

**Issue by pchiang5** [YosefLab/scVI#560]
Hi,

After the harmonization, is it possible to add the cluster numbers and umap information back to the original loom files? I would like to import them into SCE or Seurat objects in R console.

Thanks

**Comment by adamgayoso** [comment]
I don't think this is a functionality that we plan to implement in scVI. I don't use loom much, but it seems it would be easier to write those as csvs to load in R.

Alternatively, there's a way to load AnnData objects with Seurat now I believe.

**Comment by pchiang5** [comment]
Thank you for your answer.

In this case, is there any tutorial about how to save the scVI analyses to AnnData?
