### ISSUE TITLE
GitHub landing page notebooks are for nightly, not stable version v 0.5.0 in PyPi, this is confusing.

### ISSUE THREAD

**Issue by aa-m-sa** [YosefLab/scVI#568]
I spent an annoying amount of time trying wondering why the tutorial notebooks did not work (`.settings` did not have function `set_seed` etc) with the scVI v.0.5.0 I installed with pip.

Please clarify the GitHub landing page, e.g. separate documentation for stable 0.5.0 that links to notebooks that work with stable version, ditto for nightly.

**Comment by romain-lopez** [comment]
Hi, 

Thanks this is a good point that we will address ASAP.

Best, 
Romain

**Comment by adamgayoso** [comment]
We decided to set up a dev branch and make github point to the stable branch automatically
