### ISSUE TITLE
Suggestion on incorporation continuous covariates for batch correction

### ISSUE THREAD

**Issue by davemcg** [YosefLab/scVI#571]
First - scVI is great! It's the best performer at my project integrating highly disparate datasets.

My best integration's UMAP projection shows some 'grouping' by percent mitochondrial gene expression (I am filtering to remove cells with >10% mt gene expression) and some small effect from number of unique RNA features.

I don't think there's a way of feeding a continuous covariate in `VAE`. 

Would you have any recommendations on how to correct for this? 

Should I remove scVI latent dimensions which show clear stratification by these covariate(s)? 

Should I consider scaling the raw counts by percent mito gene expression?

Thanks,
David

**Comment by adamgayoso** [comment]
Thank you David. There is not a straightforward way to incorporate continuous covariates in the VAE class. In fact, there are several ways we could go about modeling this, so I'm not sure in what time period we will see this. And even for one way to model these covariates, there are several implementation options. Therefore, some planning is required. 

That said, you could correlate each latent dimension with some MT score and remove dimensions this way. This seems like a reasonable compromise for now. I would imagine there would be 1 or 2 latent dimensions that clearly "explain" the MT gene expression. 

Another immediately easier thing (but perhaps unsatisfying) is to try adding more batches corresponding to MT high and MT low, for example.

Also out of curiosity, are there any MT genes in the scVI dataset?

@romain-lopez any other thoughts?

**Comment by davemcg** [comment]
Thanks Adam,

I've removed all MT genes from consideration in feature selection. Still, apparently some other genes are correlated with higher MT gene expression/capture. 

I agree the most straightforward thing is the check each latent dimension to see which (if any) are correlated with continuous variables of interest. 

Thanks for your time,
David

**Comment by romain-lopez** [comment]
Hi David, 

Indeed so far I think that Adam described all the possible options. When we get more time we will be able to push some code that shows how to do that.

Best, 
Romain

**Comment by adamgayoso** [comment]
@davemcg it would be helpful if you reported back with what worked for you!

**Comment by adamgayoso** [comment]
Cross-linking this with #364 .
