### ISSUE TITLE
export scVI analyses to AnnData

### ISSUE THREAD

**Issue by pchiang5** [YosefLab/scVI#572]
Thank you for your answer.

In this case, is there any tutorial about how to save the scVI analyses to AnnData?

#=====================================
I don't think this is a functionality that we plan to implement in scVI. I don't use loom much, but it seems it would be easier to write those as csvs to load in R.

Alternatively, there's a way to load AnnData objects with Seurat now I believe.

--

**Comment by adamgayoso** [comment]
So we have some details in both the basic tutorial and scanpy tutorial. I'm not sure how the AnnData to Seurat works but I also just learned of something called sceasy that might aide this interoperability.

**Comment by pchiang5** [comment]
Yes, I also found the link converting AnnData to Seurat. 

Could you kindly provide the links for saving the scVI analysis posterior to AnnData?

**Comment by adamgayoso** [comment]
Please search for references to `post_adata`.

https://nbviewer.jupyter.org/github/YosefLab/scVI/blob/master/tests/notebooks/basic_tutorial.ipynb
