### ISSUE TITLE
Subsampling bug when using AnnDatasetfromAnnData

### ISSUE THREAD

**Issue by mukundvarma** [YosefLab/scVI#584]
I'm using `AnnDatasetFromAnnData` as part of a larger pipeline, with the following invocation:
```
        gene_dataset = AnnDatasetFromAnnData(adata, batch_label="batch")
```
For whatever reason, when initializing the AnnDataset object, (likely in the self.populate_from_dataset call), the number of cells included becomes larger than the initial number of cells. I'm not sure if this is a bug in the `update_cells` function or elsewhere.

Here's the output from scvi.

```
[2020-02-14 16:08:15,164] INFO - scvi.dataset.dataset | Remapping labels to [0,N]
[2020-02-14 16:08:15,165] INFO - scvi.dataset.dataset | Remapping batch_indices to [0,N]
[2020-02-14 16:08:15,268] INFO - scvi.dataset.dataset | Computing the library size for the new data
[2020-02-14 16:08:15,369] INFO - scvi.dataset.dataset | Downsampled from 16501 to 16456 cells
```

It seems like there should be checks that `new_nb_cells` should be less than or equal to `nb_cells` and that the new obs names should be a subset of old obs names.

Any idea where the problem might be, and what a solution could be?

*Version of scvi:* 0.5.0
*OS information:* x86_64 GNU/Linux (AWS instance)

**Comment by adamgayoso** [comment]
How many cells are in adata? Are you able to check if `extract_data_from_anndata()`  in anndataset.py works?

**Comment by mukundvarma** [comment]
adata.obs["batch"] is made of ints. There are 16501 cells in adata. adata.obs['batch'] is int64s. 

It was subsetted on (highly variable) genes (from ~50000 to 3000), but not cells. 

Thanks for the quick reply!

**Comment by adamgayoso** [comment]
Am I missing something?

```
[2020-02-14 16:08:15,369] INFO - scvi.dataset.dataset | Downsampled from 16501 to 16456 cells
```
This just removed empty cells.

**Comment by mukundvarma** [comment]
That's my bad, sorry about that. Closing this issue.

**Comment by adamgayoso** [comment]
No worries!
