### ISSUE TITLE
handle gene attribute and cell attribute of the same name

### ISSUE THREAD

**Issue by hy395** [YosefLab/scVI#608]
Hi,
I notice that if you happen to have the same gene attribute name and cell attribute name in anndata (e.g. **n_counts** if you use scanpy filter_genes and filter_cells to count UMI), scvi **populate_from_data** function will overwrite the cell attribute with the gene attribute without given a warning, and later encounters error in **filter_cells_by_count**. Maybe it would be helpful to:
1) give a warning in **initialize_cell_attribute** when an attribute name already exist.
2) add _cell and _gene suffix to all attribute names so all of them will be unique?
I am happy to make a PR if it would be useful.

**Comment by adamgayoso** [comment]
So just to reiterate, you're suggesting that if an attribute name already exists in the scvi dataset object, and one attempts to initialize a new cell or gene attribute with the already existing name, that we provide a warning and append `_cell` or `_gene` to the new attribute name accordingly?

If so, I think that would be useful if you're willing to make a PR.
