### ISSUE TITLE
AnnDatasetFromAnnData deletes data

### ISSUE THREAD

**Issue by aopisco** [YosefLab/scVI#617]
<img width="1014" alt="Screen Shot 2020-03-13 at 12 31 14 PM" src="https://user-images.githubusercontent.com/25906087/76653752-90292680-6526-11ea-92b1-2494da71de56.png">

**Comment by adamgayoso** [comment]
Thank you for pointing this out. We will address this ASAP!

**Comment by adamgayoso** [comment]
For now you can use `adata.copy()` as the input to our class.

**Comment by adamgayoso** [comment]
@aopisco we just release 0.6.1 on pip, which fixes this issue
