### ISSUE TITLE
scvi.dataset import issue

### ISSUE THREAD

**Issue by sshen82** [YosefLab/scVI#625]
Hi,
I am trying to use scvi, but as long as I use scvi.* (for example, scvi.dataset, scvi.inference, ....), it doesn't work at all. However, if I directly import scvi, it works fine.

```
from scvi.dataset import CsvDataset
import urllib.request
import os

remote_csv_dataset = scvi.dataset.CsvDataset("chr1_scvae.csv",
                                save_path = "/u/s/s/sshen82/Documents")
```

Traceback (most recent call last):
  File "scvi.py", line 1, in <module>
    from scvi.dataset import CsvDataset
  File "/afs/cs.wisc.edu/u/s/s/sshen82/Documents/scvi.py", line 1, in <module>
    from scvi.dataset import CsvDataset
ModuleNotFoundError: No module named 'scvi.dataset'; 'scvi' is not a package

**Comment by adamgayoso** [comment]
Can you describe how you installed scvi?

**Comment by sshen82** [comment]
I use "pip install scvi".

**Comment by adamgayoso** [comment]
This is a bit odd, I just double checked on my end and have no issues on a fresh virtualenv. What version of python do you have? Are you installing in a virtualenv?

**Comment by sshen82** [comment]
Python: 3.7.4
I am not sure what virtualenv is, but I wrote "virtualenv --version" and it responded 15.1.0.

**Comment by adamgayoso** [comment]
how did you install python? You may need to use pip3?

**Comment by sshen82** [comment]
I tried to install that using pip3 as well, and it doesn't work. I also tried to clone the one in github, but it doesn't work as well...

**Comment by adamgayoso** [comment]
I believe this is a python configuration issue on your end. It would be helpful if you installed scVI in a virtual environment and reported back if you still have the same issue.

**Comment by adamgayoso** [comment]
Also, there is a bug in the code snippet you sent. It should be:

```
from scvi.dataset import CsvDataset
import urllib.request
import os

remote_csv_dataset = CsvDataset("chr1_scvae.csv",
                                save_path = "/u/s/s/sshen82/Documents")
```
