### ISSUE TITLE
Function to obtain l_n

### ISSUE THREAD

**Issue by sshen82** [YosefLab/scVI#628]
Hi, 
I am wondering which function it is to get l_n in the paper for each cell? The closest one is "sample_from_posterior_l", but the output dimension is (batch_size, 1) rather than (n_cells, 1).

**Comment by adamgayoso** [comment]
Please use the `get_stats()` function in the posterior class.

e.g.

```python
l_n = full_posterior.get_stats()
```

**Comment by sshen82** [comment]
OK, thank you for your help!
