### ISSUE TITLE
annotation with SCANVI

### ISSUE THREAD

**Issue by pchiang5** [YosefLab/scVI#632]
Hello,

I have a concatenated dataset from 6 sources for cell annotation. Among them, #1, #4, and #5 serve as a reference with cell-type information at slots all_dataset.CellTypes. If I would like to annotate the rest of the samples (#2, #3, and #6) with SCANVI. How shall I perform the analysis?

When I did the concatenation as 

`all_dataset.populate_from_datasets([XXX, XXX,...])`

It showed error:
> ValueError: Reference mapping cell_types for labels merging is not registered in all datasets.

Although adding "shared_labels= False" avoided the problem, how could SCANVI identify cell-type information within the dataset? 
`all_dataset.populate_from_datasets([XXX, XXX,..., shared_labels=False)`

Further, I could run with the code below, but apparently the reference samples were not induced. How shall I point them out for annotation?

```
scanvi = SCANVI(all_dataset.nb_genes, n_batch=all_dataset.n_batches, n_labels=all_dataset.n_labels, n_hidden=128, n_latent=10, n_layers=2, dispersion="gene-batch", dropout_rate=0.1, reconstruction_loss="zinb")
trainer = SemiSupervisedTrainer(scanvi, all_dataset, use_cuda=True, n_epochs_kl_warmup=None,  train_size=0.5)
trainer.train(n_epochs=200)

```

Thanks.

**Comment by romain-lopez** [comment]
Hi, 

Please refer to the annotation notebook for the use of scANVI and the method "labelled_set" which is what you need here.

https://github.com/YosefLab/scVI/blob/master/tests/notebooks/annotation.ipynb

**Comment by pchiang5** [comment]
Thank you @romain-lopez

I ran smoothly following the tutorial. However, something was wrong about the loaded GeneExpressionDataset object from my own imported loom file in the following manner:


`droplet = LoomDataset('droplet.loom', save_path=save_path,  cell_types_attribute_name="CellTypes" )
  `
The cell_types attribute was null and the "CellTypes" attribute was incorrect (dtype=object instead of <U128)compared with the simulation_1 from the tutorial:

```
>>> droplet.cell_types
>>> droplet.CellTypes
array(['cell1', 'cell1', 'cell1', ...,
       'cell4', 'cell2', 'cell5'],
      dtype=object)
>>> simulation_1
GeneExpressionDataset object with n_cells x nb_genes = 20000 x 2000
    gene_attribute_names: 'gene_names'
    cell_attribute_names: 'batch_indices', 'local_vars', 'local_means', 'labels'
    cell_categorical_attribute_names: 'batch_indices', 'labels'
>>> simulation_1.cell_types
array(['type1', 'type5', 'type4', 'type2', 'type3'], dtype='<U128')
```

How can I load the file for proper cell_types and labels attributes (or impart the attributes after loading) for further populate_from_datasets()?

**Comment by adamgayoso** [comment]
I suspect this could be an issue with the loom dataset loader. It would be helpful if you could load the loom file using the [Anndata API ](https://anndata.readthedocs.io/en/stable/anndata.read_loom.html#anndata.read_loom). Then, ensure the the resulting `adata` has `adata.obs[cell_type_key]`. Then, you can use our Anndataset loader while specifying the cell type label argument.

**Comment by pchiang5** [comment]
The loading from anndata.read_loom() worked for getting correct cell_types and labels in the GeneExpressionDataset object. However, a different error occurred when I tried merging the datasets. 


```

>>> all_dataset.populate_from_datasets([droplet, reference])
[2020-04-07 13:37:45,709] INFO - scvi.dataset.dataset | Merging datasets. Input objects are modified in place.
[2020-04-07 13:37:45,710] INFO - scvi.dataset.dataset | Gene names and cell measurement names are assumed to have a non-null intersection between datasets.
[2020-04-07 13:37:45,811] INFO - scvi.dataset.dataset | Keeping 21117 genes
[2020-04-07 13:37:52,177] INFO - scvi.dataset.dataset | Computing the library size for the new data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\dataset\dataset.py", line 338, in populate_from_datasets
    dataset.reorder_genes(first_genes=genes_to_keep, drop_omitted_genes=True)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scvi\dataset\dataset.py", line 1037, in reorder_genes
    setattr(self, attribute_name, attr[new_order])
TypeError: only integer scalar arrays can be converted to a scalar index 
```

The same datasets merged well for harmonization when I loaded with LoomDataset(). How shall I address the issue?

**Comment by adamgayoso** [comment]
Thanks for updating. I think you've actually revealed a bug regarding the TypeError you got. I'll fix this soon!
