### ISSUE TITLE
ScanVI harmonization notebook is not about ScanVI

### ISSUE THREAD

**Issue by ANazaret** [YosefLab/scVI#639]
I was going through the Harmonizing data with scVI and scANVI notebook and there is actually no use of ScanVI. Is this wanted?

**Comment by adamgayoso** [comment]
No, I believe this issues is related to #624

**Comment by adamgayoso** [comment]
I leave the creation of such tutorial to @romain-lopez and @chenlingantelope :)

**Comment by adamgayoso** [comment]
Closing as this issue is related to #624
