### ISSUE TITLE
Unexpected keyword argument 'batch_label' error when calling AnnDatasetFromAnnData() function

### ISSUE THREAD

**Issue by claudiadast** [YosefLab/scVI#647]
I have made a docker container that uses a Python 3.6 base image and I use conda to install the following packages:

```
name: myenv
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scvi
  - awscli
  - boto3
  - scanpy
  - dataclasses
  - anndata
  - pytorch
```

Within my container, I have a python script that has the following line:

```
from scvi.dataset import AnnDatasetFromAnnData

scviDataset = AnnDatasetFromAnnData(adata,batch_label="batch_indices")
```

When I try to run my container, that line raises the following error: `TypeError: __init__() got an unexpected keyword argument 'batch_label'`

This error made me think there might be a version incompatibility issue, so I checked the version number of `anndata`, which is `Version('0.7.1')`. Which version of `anndata` is `scVI` expecting? Is that what's causing the above error?

**Comment by PierreBoyeau** [comment]
Hi!
Could you provide the scVI version in the container and the full traceback?

**Comment by claudiadast** [comment]
Hi! The scVI version is '0.4.1'. And attached is a snapshot of the Traceback! 

<img width="673" alt="Screen Shot 2020-04-02 at 3 48 10 PM" src="https://user-images.githubusercontent.com/16655465/78306921-6fd30300-74f9-11ea-927e-d1b86cc4f365.png">

**Comment by PierreBoyeau** [comment]
Thanks! As of today, scVI does not support python 3.6. Could you upgrade to 3.7?

**Comment by adamgayoso** [comment]
Ah also this functionality was not available in 0.4.1. We recommend upgrading to the newest version (0.6.3)

**Comment by claudiadast** [comment]
@adamgayoso Ahh okay, I figured it might be that. I'll try upgrading to that newer version first, and then if it still doesn't work, I'll upgrade to 3.7!

**Comment by adamgayoso** [comment]
Great, you should be able to run scVI on python 3.6 if you install dataclasses.

**Comment by claudiadast** [comment]
Oh okay, I just tried building the container with scVI=0.6.3, but then I got a whole bunch of package conflicts (too long to post here), and the dataclasses package was included already in my YML file. Looks like Python 3.7 is my only option?

**Comment by adamgayoso** [comment]
Possibly, please let me know if there is an issue with 3.7!

**Comment by adamgayoso** [comment]
@claudiadast I also updated the conda recipe so 3.6 should work now
