### ISSUE TITLE
LLVM version dependency for llvmlite

### ISSUE THREAD

**Issue by paulmenzel** [YosefLab/scVI#657]
*llvmlite* 0.30.0 does not seem to support LLVM 9.0, so the instructions – at least in Debian Sid/unstable with LLVM 9.0 as default – need to be `LLVM_CONFIG=llvm-config-8 pip install scvi`. Otherwise `llvm-config` cannot be found for building *llvmlite*.

**Comment by adamgayoso** [comment]
I just released 0.6.4 which should address this. Would you be able to try installing that version with pip and let me know if you have the same issue?
