### ISSUE TITLE
Adding compatibility with biom-format

### ISSUE THREAD

**Issue by mortonjt** [YosefLab/scVI#660]
Biom-format is a commonly used file format for microbiome studies.
It boils down to an hdf5 format of scipy.sparse.csr_matrix that also includes sample / gene metadata.

Paper of the file format is here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3626512/

Let me know if there is any interest in this. I've already implemented the [torch.dataset](https://github.com/mortonjt/scVI/pull/1) and will be happy to push in a PR.

**Comment by romain-lopez** [comment]
Hi,

Thanks for your contribution! I am not familiar with biomformat. Do people use this for scRNA-seq or is it some other kind of data? If so, why is it of interest to the users of scVI? Should we add microbiome datasets URLs to the codebase, as well as a notebook of how to analyze this data with scVI? 

I'd be happy to add this to the codebase provided this will be useful.

Best, 
Romain

**Comment by mortonjt** [comment]
I haven't seen this used for scRNA-seq, but I see no reason why it can't be done.  The biom-format just provided a compressed format for storing sparse matrices (in addition to accompanying feature / sample metadata).

I don't see any problem including microbiome datasets + notebooks.  Is there a preferred location for storing datasets? (i.e. zenodo?)

**Comment by romain-lopez** [comment]
Hi, 

Usually we add the datasets in the scVI-data github repo https://github.com/YosefLab/scVI-data but naturally if those datasets are already hosted online and can be fetched with a wget this is definitely the preferred method (you can look into the Downloadable dataset class). We do this for example for 10x datasets.

We now have a contributed notebook section in readthedocs, so if you want to show how a model of our codebase can be applied to microbiome we will have a look and post it to Colab. One example is https://scvi.readthedocs.io/en/stable/contributed_tutorials/scVI_DE_worm.html

Best, 
Romain

**Comment by adamgayoso** [comment]
I would be happy to integrate this in scVI but a few points:

- we are going to refactor the dataset module a bit to have simple `read_biom(path)` functions
- we should not make biom a strict requirement, and can instead just catch an `ImportError`
- we should have a tutorial describing how to use scVI with microbiome data

As @romain-lopez said, it can be a contributed tutorial. @mortonjt, would you be able to make a simple tutorial like the LDVAE one? As well as make the PR after we refactor the dataset module (< 1 month time)?

**Comment by mortonjt** [comment]
Hopefully it shouldn't take a month XD. 
See pull request here: https://github.com/YosefLab/scVI/pull/675

**Comment by adamgayoso** [comment]
@mortonjt, so we are creating a new dataset API that relies entirely on anndata. Since it seems pretty easy to go from biom to anndata, I think it would be helpful after we get the new API merged, to edit your tutorial with a function to download and make the biom file into an anndata and then proceed with the rest of the tutorial. Therefore, the `BiomDataset` class you made should be no longer necessary. Sorry for all the changes! It's probably best to wait at this point and see how our new API will work before fixing this, of course if you're still interested in contributing the tutorial.

**Comment by mortonjt** [comment]
Got it. No worries

**Comment by adamgayoso** [comment]
We addressed this by adding a `to_anndata` function in biom. 

https://github.com/biocore/biom-format/pull/845

**Comment by mortonjt** [comment]
Great, thanks @adamgayoso !

**Comment by adamgayoso** [comment]
@mortonjt we've finished most of the large changes for scvi-tools. We would still appreciate a simple tutorial with application to microbiome data, if you're able to contribute it. It would just need to be a google colab notebook that includes data download, model running, etc. Similar to the other notebooks we have in the user guide. Feel free to reach out on gitter (https://gitter.im/scvi-tools/development) if you're interested.

**Comment by mortonjt** [comment]
That's good news!!  If it is just a tutorial that shouldn't be a problem -
we have a couple of ongoing projects using scvi; will be more than happy to
share once they are in a shareable state :)

**Comment by mortonjt** [comment]
Hi @adamgayoso thank you for your contribution to biom earlier - we ended up using that in order to benchmark LDVAE.  
Our tool can be found here : https://github.com/flatironinstitute/catvae with the LDVAE script [here](https://github.com/flatironinstitute/catvae/blob/master/scripts/ldvae.py). Paper is [here](https://www.biorxiv.org/content/10.1101/2021.11.09.467939v1) if there is interest.

If there is interest in the Multinomial VAE methodology we implemented, feel free to follow up, I'll be happy chat.
