### ISSUE TITLE
suggestion: trainer.save and load functions

### ISSUE THREAD

**Issue by allonw** [YosefLab/scVI#666]
that wrap the torch.save but will also save convergence history, run parameters etc.

**Comment by adamgayoso** [comment]
Could you explain what outputs you'd want specifically? I'm not sure if you've seen our new posterior saving and loading (which also saves the trained model and dataset object). It's described in section 1.3.1 in the basic tutorial.

**Comment by allonw** [comment]
yes, you're right, I didn't notice a new posterior saving was introduced, I'll give it a try!
