### ISSUE TITLE
Model training loss was Nan

### ISSUE THREAD

**Issue by CFrangieh** [YosefLab/scVI#667]
Hi

I am going through the totalVI tutorial (https://scvi.readthedocs.io/en/stable/tutorials/cite_scrna_integration_w_totalVI.html) with my own CITE-seq dataset. I downsampled to 4000 genes and have 24 CITE antibodies. When I call trainer.train() I first get the following warning: "WARNING - scvi.inference.trainer | Model training loss was NaN" followed by the error: "ValueError: The parameter mu has invalid values"

I am initializing the TOTALVI model with 1 batch with the following line: 
totalvae = TOTALVI(dataset.nb_genes, len(dataset.protein_names), n_batch=dataset.n_batches)

And initializing the TotalTrainer module with:
trainer = TotalTrainer(totalvae, dataset, train_size=0.90, test_size=0.10, use_cuda=False, frequency=1, batch_size=256, use_adversarial_loss=True)

Can you advise?

Thanks

**Comment by adamgayoso** [comment]
Hello, 

Is your intention to integrate with scRNA data? If not, I recommend following the other [totalVI tutorial](https://scvi.readthedocs.io/en/stable/tutorials/totalvi.html). 

When you are only analyzing one batch, it's not necessary to specify `n_batch` when you initialize the model.

**Comment by CFrangieh** [comment]
Yes – the AnnData object has both RNA (23,000 genes) and CITE (24 antibodies) for each cell in the format specified in the tutorial. Genes are then downsampled using “dataset.subsample_genes(4000)”

**Comment by adamgayoso** [comment]
Sorry I'm still a bit unclear, the tutorial you linked is for the case where you have one dataset (batch) with only RNA and one dataset (batch) with RNA + protein (i.e., CITE-seq dataset). 

I believe what you want is to follow the other tutorial I linked with the caveat that you only have one CITE-seq dataset -- so there would be no `dataset1` or `dataset2`, you'd have just one `dataset`

**Comment by CFrangieh** [comment]
I was using the tutorial where one dataset is missing CITE counts, but I was ignoring the batch part and ignore the part where one group of CITE counts is set to zero. If I also ignore batch specific lines in the tutorial you linked, it seems like I have the same code with the exception of use_adversarial_loss not being True (and omitting `n_batch` as you pointed out).

When I follow that tutorial I am getting the same error. Here are the 7 lines I am gathering that I should run from both tutorials:

```
totalVI_all = AnnDatasetFromAnnData(adata, cell_measurements_col_mappings= 
                                                              {"protein_expression":"protein_names"})
dataset = GeneExpressionDataset()
dataset.populate_from_datasets([totalVI_all])
dataset.subsample_genes(4000)
totalvae = TOTALVI(dataset.nb_genes, len(dataset.protein_names))
trainer = TotalTrainer(totalvae, dataset, train_size=0.90, test_size=0.10, use_cuda=False, 
                                   frequency=5, batch_size=256)
trainer.train(lr=4e-3, n_epochs=500)
```

And the error:

```
WARNING - scvi.inference.trainer | Model training loss was NaN
*** ValueError: The parameter mu has invalid values
```

On a Linux machine running RedHat 7.6

**Comment by adamgayoso** [comment]
Yes, this is correct though you even just do 

```python
dataset = AnnDatasetFromAnnData(adata, cell_measurements_col_mappings={"protein_expression":"protein_names"})
```
Just to confirm, have the data been normalized in any way? totalVI expects the data to be UMI counts.

**Comment by CFrangieh** [comment]
I am using raw UMI counts for both RNA and CITE data. I am building my AnnData structure from scratch using:

```
adata = anndata.AnnData(X=RNA_UMI_counts)
adata.var = pd.DataFrame(index=RNA_gene_names)
adata.obs = pd.DataFrame(index=cell_barcodes)
adata.obs['Condition'] = pd.Categorical(experimental_conditions)
adata.obsm['protein_expression'] = CITE_UMI_counts
adata.uns['protein_names'] = CITE_antibody_names
```

I have 240,000 cells. I set the frequency back to 1. Reducing the learning rate to 1e-3 seems to have solved the issue. Training has not completed but the error usually occurs at or before epoch 3 and it is currently past that. Why would a learning rate that is too small result in a loss of NaN? My understanding is this would lead to slow/inefficient training or failure to find a global minimum

**Comment by adamgayoso** [comment]
So `4e-3` is a bit on the higher side, `1e-3` is the default of the Adam optimizer in pytorch. The reason we started with a "higher" one is that the early stopping procedure first tries to reduce the LR. I'm still a bit surprised that this is too high.

With 240,000 cells you likely won't need to train 500 epochs. Hopefully the early stopping kicks in. My guess is that you won't even need more than 100 epochs.

**Comment by CFrangieh** [comment]
Sounds good thanks so much for your help Adam!

**Comment by adamgayoso** [comment]
Of course! We will look into hyperparameters for larger datasets. It's definitely hard to provide a one size fits all solution.

**Comment by adamgayoso** [comment]
Btw, at 240,000 cells, if you have different 10x lanes etc, you can do

```python
adata.obs["batch_indices"] = array of int corresponding to lane starting at 0
```
Then when you initialize TOTALVI you can add `n_batch=dataset.n_batches`, this will remove the "lane" effect

**Comment by CFrangieh** [comment]
Yeah I have multiple lanes and a few experimental conditions (multiple lanes per condition). I do want to run differential expression between experimental condition so I wasn't sure if using batch corresponding to condition would be a good idea. But maybe batch according to lane would be less likely to correct biologically meaningful differences since there are multiple lanes per condition?

**Comment by adamgayoso** [comment]
Yeah this is certainly where things get tricky... were the conditions hashed in the same lane by any chance? 

Are you planning to use the DE functionality implemented in this package? If so, one thing you could do is do batch according to lane if each lane corresponds to a different condition, but when you do DE say that you have

treatment in lanes 0, 3, 4
control in lanes 1, 2

```python
tread_idx is a list of bool (mask over cells)
posterior.get_bayes_factors(treat_idx, control_idx, batchid1=[0,3,4], batchid2=[1, 2])
```
What this will do is "integrate" over the technical variation within each condition separately.

So while your choice of what you call batch will affect the latent space, since the batch effect is always added back in the decoder, you can "integrate" over them in complex ways.

Hope this makes sense!

**Comment by CFrangieh** [comment]
Yeah conditions were separated by lane, so that solution makes a lot of sense. I'll give it a try!
