### ISSUE TITLE
train_size=1 is ambiguous

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#669]
Our docstring clearly states that if you give train_size an int, it will take that many cells in the training set, but 1 is an ambiguous case as 1.0 means train on the whole dataset and 1 means train on one cell. A caveat here is that scVI skips minibatches of < 3 cells. 

We should restrict this option to only allow float between 0.0 and 1.0. Also, we need a warning statement of the training size is really low.

**Comment by romain-lopez** [comment]
Agree with this option

**Comment by romain-lopez** [comment]
I just encountered another paper that does the same mistake. @galenxing could you help us put a fix on this ASAP?
