### ISSUE TITLE
Sample out of latent, cond. on cell type and sample using scANVI.

### ISSUE THREAD

**Issue by manuflores** [YosefLab/scVI#676]
Hi scVI team, 

Is it possible to sample out of the latent space conditioning on a cell type and a sample? 

By looking at the docs, it seems that using the Posterior object, [one can only generate `n_samples` out of the posterior](https://scvi.readthedocs.io/en/stable/scvi.inference.html?highlight=generate#scvi.inference.Posterior.generate), where each of the n_samples is a count matrix with the same shape as the input. Ideally, for scANVI, it would be desirable to have a function where one can generate `n_samples` for a given cell type `c_i`, coming from a sample `s_j`, i.e. a decoder of the form q(x | c, s, z), where x is the data for a single cell across all genes and z is its latent representation. I assume that this is possible given the nature of the hierarchical model, but I found no easy way just by reading the docs and scanning through the [paper's github](https://github.com/chenlingantelope/HarmonizationSCANVI). 

My understanding (from talking to Romain) is that the differential expression function uses something similar to what I'm looking for. So maybe you could point me to it and this wouldn't need to be incorporated into the main codebase. However, if you find this helpful, I could work on it with a little guidance from the core devs to make a draft function and submit a pull request.

**Comment by adamgayoso** [comment]
So, it is currently possible to use some of our functions to make "out-of-batch" predictions. For example, `Posterior.get_sample_scale()` would give you the decoded expression and has a `transform_batch` option. In scANVI, the posterior predictive process is 

1. sample from q(z | x)
2. Feed z and batch (s) through decoder to get mean of Negative Binomial.

by transform batch, we mean setting `s` to another observed batch.

To condition on a cell type, you'd have to just take the expression of cells that you've annotated with that cell type based on the classification posterior `q(c|z)`.

**Comment by adamgayoso** [comment]
Please let me know if you have any other questions.
