### ISSUE TITLE
v0.1.4

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#68]
Let's push v0.1.14 to pip and conda after finishing #42 and #62 . 

Unfortunately I don't think anyone has written a conda recipe yet for anndata, so we'll have to create one and push it along with ours.

**Comment by jeff-regier** [comment]
Better to use a separate branch, I think, and to submit it as a pull request. Also remember to push the tags too, as described here:
https://scvi.readthedocs.io/en//latest/contributing.html#deploying

That's great you've got a recipe for anndata. It isn't essential to involve the creators anndata -- though they'll probably appreciate it -- since it's a commit to the bioconda repo not the anndata repo. Though come to think of it, it might be nice to let them know your plans by posting an issue at their repo. Maybe check whether they're willing to update it as they release new versions, or whether they have other conda-related plans.

**Comment by imyiningliu** [comment]
I'm a bit confused about how to `bumpversion` and `tag`. I tried to `bumpversion batch` with or without `git tag v0.1.4`. For both cases, I got `fatal: tag 'v0.1.3' already exists`. 

I also tried to change `__version__ = '0.1.3' ` to `__version__ = '0.1.4'` and I got `AssertionError: Did not find '0.1.3' or '__version__ = '0.1.3'' in file scvi/__init__.py`. 

Do you remember what were the procedures you used to `bumpversion`? Thanks!!

**Comment by jeff-regier** [comment]
batch? or patch? It should be `bumpversion patch`

**Comment by imyiningliu** [comment]
Ohhhh my bad .... `bumpversion patch` works
