### ISSUE TITLE
csv data format for scVI

### ISSUE THREAD

**Issue by beyondpie** [YosefLab/scVI#683]
Hi there! 

scVI looks really nice.  I want to give it a try.  I use the symsim to simulate the dataset, like gene by cells.  Then how can I let the scVi read the dataset?  

For csv file, I read the document, but not sure the "real" format of csv. Should I only use gene by cell count or should I add gene name or cell name in the file? Could you show me a demo csv file?

Thanks!

**Comment by galenxing** [comment]
Hi @beyondpie! 

For an example of loading a csv dataset checkout: [https://github.com/YosefLab/scVI/blob/master/tests/dataset/test_csv.py](https://github.com/YosefLab/scVI/blob/master/tests/dataset/test_csv.py)

It loads from this sample test dataset: `scVI/tests/data/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv.gz`. It's okay to have gene names and cell names in the file. 

If your dataset is not gene by cell, then you can set the  `gene_by_cell`  param in CsvDataset to `false`, by default it is `true`.

For full list of parameters, check out [https://scvi.readthedocs.io/en/stable/_modules/scvi/dataset/csv.html#CsvDataset](https://scvi.readthedocs.io/en/stable/_modules/scvi/dataset/csv.html#CsvDataset)

**Comment by beyondpie** [comment]
@galenxing 
Thanks, this is really helpful!

**Comment by beyondpie** [comment]
@galenxing 
`gene_by_cell` means the rows are genes? But from the test dataset, actually the columns are genes. So what's the definition of gene_by_cell?

**Comment by galenxing** [comment]
@beyondpie yea `gene_by_cell` means the rows are genes. The columns in the test dataset are barcodes which is a proxy for cells (since you can have doublets or triplets during sequencing the term cell might not be fully accurate).

**Comment by beyondpie** [comment]
Thank you. I made a mistake in my code so that I didn't get the right matrix.
