### ISSUE TITLE
Unexpected arguments with AnnDatasetFromAnnData() and get_sample_mixing()

### ISSUE THREAD

**Issue by notimenocall** [YosefLab/scVI#690]
I was trying to re-run what is demonstrated on the totalVI tutorial and ran into errors with 1)
dataset = AnnDatasetFromAnnData(
    ad=anndataset,
    cell_measurements_col_mappings={"protein_expression":"protein_names"},
)
with an error message saying unexpected keyword argument 'cell_measurements_col_mappings'.
2) get_sample_mixing()
with error message get_sample_mixing() got an unexpected keyword argument 'transform_batch'
​I use the stable version. Any idea why? Thanks much!

```python
[CODE HERE]
```

**Comment by adamgayoso** [comment]
Could you confirm exactly which version of scvi you are using? `scvi.__version__`

**Comment by adamgayoso** [comment]
I suspect you're not using the newest version of scvi. Please try upgrading your scvi version e.g., `pip install --upgrade scvi`

**Comment by notimenocall** [comment]
Yes, you are right. For some reason I used the older version from another environment. Sorry for the stupid mistake. Thanks!

**Comment by adamgayoso** [comment]
No worries!
