### ISSUE TITLE
ImportError: cannot import name 'AnnDatasetFromAnnData' 

### ISSUE THREAD

**Issue by cartal** [YosefLab/scVI#695]
Hi, I've been trying to run the latest version of `scVI`, but I keep getting this error when I try to load my `adata`.

```
ImportError: cannot import name 'AnnDatasetFromAnnData' from 'scvi.dataset.dataset' (/Users/ctl/anaconda3/lib/python3.7/site-packages/scvi/dataset/dataset.py)
```

```
ImportError                               Traceback (most recent call last)
<ipython-input-2-97852c81aa89> in <module>()
     13 
     14 from scvi.dataset.dataset import GeneExpressionDataset
---> 15 from scvi.dataset.dataset import AnnDatasetFromAnnData
     16 from scvi.inference import UnsupervisedTrainer
     17 from scvi.models import SCANVI, VAE

ImportError: cannot import name 'AnnDatasetFromAnnData' from 'scvi.dataset.dataset' (/Users/ctl/anaconda3/lib/python3.7/site-packages/scvi/dataset/dataset.py)

```

#### Versions:

> '0.6.5'

**Comment by adamgayoso** [comment]
Hello,

Please try importing using `from scvi.dataset import AnnDatasetFromAnnData` and same with `GeneExpressionDataset`

**Comment by cartal** [comment]
Hi, 

I've tried that already and this is the result: 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-50ed3206d44b> in <module>
     12 import scanpy as sc
     13 
---> 14 from scvi.dataset import AnnDatasetFromAnnData
     15 from scvi.dataset import GeneExpressionDataset
     16 from scvi.inference import UnsupervisedTrainer

ImportError: cannot import name 'AnnDatasetFromAnnData'
```

**Comment by adamgayoso** [comment]
how did you install scvi?

**Comment by cartal** [comment]
I used `conda install scvi -c bioconda -c conda-forge` in one machine and `pip install scvi` in another one. Both of them have the same problem.

**Comment by adamgayoso** [comment]
My guess is that this has something to do with your python setup as you can test with the tutorials in google colab that the imports work fine; though I'm installing from conda in a fresh environment to test the conda installation.

Is it just the anndata class? or the trainer classes too?

**Comment by adamgayoso** [comment]
I just installed using `conda install scvi -c bioconda -c conda-forge` in a fresh conda environment and cannot reproduce the issue. @galenxing any ideas?

**Comment by galenxing** [comment]
Hey @cartal, it seems you have an extra `.dataset` in your import statement. 

The preferred import is `from scvi.dataset import AnnDatasetFromAnnData`
or explicitly:  `from scvi.dataset.anndataset import AnnDatasetFromAnnData`

**Comment by galenxing** [comment]
Hi @cartal, are you running this outside of the scVI folder? I also can't replicate this error. I would suggest a clean install of scVI.

**Comment by cartal** [comment]
Hi guys, many thanks for the support on this one. 

Since I'm installing `scVI` through `conda` and/or `pip`, I don't use the `scVI` folder at all. Should I install it from source?

I have created a new conda environment and installed `scVI` there after cleaning all possible installations using either pip or conda. I still get the same error.

**Comment by adamgayoso** [comment]
This is quite confusing

`from scvi.dataset.dataset import GeneExpressionDataset`

this works because `scvi.dataset.dataset` is the path for the file containing this class.  But in general, you should not have to resort to this. Do you have issues with other packages?

**Comment by cartal** [comment]
Nope, I don't. 

I have now tried on a couple of cloud machines and my laptop and I have the same problem. I will try another fresh installation as well, to see if there is an issue with my environments. But I don't think this is the problem.

**Comment by adamgayoso** [comment]
How is python installed? And what version of python are you using?

**Comment by cartal** [comment]
Python is install with conda, and I'm using `python=3.7`. For a clean installation I make sure all packages are removed and then I create the environment with:

```
conda create -n scVI python=3.7
```

Then I install `scVI` via `conda`.

**Comment by galenxing** [comment]
Can you run `import scvi; print(scvi.__file__)` and post the output?

**Comment by romain-lopez** [comment]
Hi @cartal, I just checked those lines again on Colab, and it works fine.

!pip install scvi[notebooks]
import scvi
from scvi.dataset import AnnDatasetFromAnnData

I really am not sure where this could come from? Is it possible your conda installation is corrupted? Not sure since you said you tried on several machines? I think @galenxing also tried a fresh install and it succeeded. This is quite puzzling

**Comment by adamgayoso** [comment]
Unfortunately we are still unable to reproduce this. Feel free to reach out personally and we can try to help over email!
