### ISSUE TITLE
Redo data loading tutorial

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#702]
1. We should show with some basic commands how to setup the anndata for our models, while pointing to the anndata/scanpy API for loading personal data from loom/csv/h5ad etc. 
2. We highlight the 10x dataset function and one of our preloaded datasets and reference the docs for other pre loaded datasets
3. We have an advanced part showing what we do to the anndata object and how this is interpreted by our data loader.

**Comment by galenxing** [comment]
Done!
