### ISSUE TITLE
Training without batch labels

### ISSUE THREAD

**Issue by gprashant123** [YosefLab/scVI#703]
I am trying to implement scVI on a single-cell dataset and although I do not have the batch annotations for it, through the literature I am aware that it consists of 2 batches. While training using the VAE command, I specified the number of batches as 2. Would this still mean that the mean and standard deviation parameters of the size factors will be a vector of size 2?

In other words, does specifying only the number of batches without explicitly giving the annotations automatically predict the probable batch index of each cell? 

Also, is there a function to get the size factors from the trained model?

**Comment by adamgayoso** [comment]
If I'm understanding your question correctly, then no, it's not possible for scVI to automatically infer which batch a cell came from, as scVI assumes that the batch annotations are given. The `Posterior` function `.get_stats()` returns the size factor. It will always be a scalar. When there are multiple batches, the prior distribution is set empirically per batch.

**Comment by gprashant123** [comment]
Yes, that was my question, thanks!

**Comment by adamgayoso** [comment]
If there is a batch effect, perhaps you could separate cells based on PC1 or PC2 and try to assign a batch label that way.
