### ISSUE TITLE
Assessing the training of the model

### ISSUE THREAD

**Issue by gandladm** [YosefLab/scVI#710]
Hi, I am a student working on running the totalVI model at KITE pharma. I have recently been applying and following the totalVI tutorial. How do I assess the “Negative ELBO over training epochs” plot? More specifically, how do I assess whether the model has trained sufficiently from this plot?

**Comment by adamgayoso** [comment]
I don't have an exact answer for you, but generally you're looking to see if the ELBO does not improve on held-out data, or improves really slowly. Feel free to post your training history here.
