### ISSUE TITLE
Scanpy version pinned to >=1.5.1 necessary?

### ISSUE THREAD

**Issue by LuckyMD** [YosefLab/scVI#713]
Hey!

I was wondering whether the scanpy version pin to >=1.5.1 is necessary. Do you rely on e.g., the location of the stored connectivities matrix somewhere? We are working with version 1.4.6 in our benchmarking project at the moment which contains code that is not compatible with 1.5.1 yet.

**Comment by adamgayoso** [comment]
Hi @LuckyMD, it seems like we bumped scanpy with our 0.6.6 release. @galenxing do you remember why? 

For your project, since you're just using scVI it should be fine to use version 0.6.5, which has scanpy > 1.4 requirement.

**Comment by LuckyMD** [comment]
Hey @adamgayoso! Thanks so much for the quick reply.

We noticed there was only `_highly_variable_genes` from scanpy in here. We are however now also considering to test scANVI for which there was apparently a bug until 0.6.6. So we're unfortunately a bit stuck on this. Do you think it would be possible to remove the requirement? Otherwise we would just make a fork without it and use that i guess (a bit more messy for a benchmark though).

**Comment by adamgayoso** [comment]
I see, we will test out a 0.6.7 with removing these requirements.

**Comment by LuckyMD** [comment]
Thanks a lot!

**Comment by adamgayoso** [comment]
We should be able to make a release tomorrow.

**Comment by LuckyMD** [comment]
You are awesome :). That might be just in time to set up our runs before i head on vacation tomorrow :).

**Comment by adamgayoso** [comment]
0.6.7 is now on pypi

**Comment by LuckyMD** [comment]
Thanks!
