### ISSUE TITLE
errors when calling get_harmonized_scale()

### ISSUE THREAD

**Issue by uhcnivag** [YosefLab/scVI#719]
Hi, thanks for your previous answer in issue #287 that get_harmonized_scale(fixed_batch=batchid) returned normalized data matrix. I updated scVI to 0.6.7 recently and found errors (no such attributes) when calling get_harmonized_scale(). May I know if the function is re-named? Tried finding answer in Docs but no luck. Thanks!

**Comment by adamgayoso** [comment]
Hello,

The new version uses `get_sample_scale(transform_batch=batchid)`. The documentation page is [here](https://scvi.readthedocs.io/en/stable/api/scvi.inference.Posterior.html#scvi.inference.Posterior.get_sample_scale).

**Comment by uhcnivag** [comment]
Ohh I see. Thanks a lot!
