### ISSUE TITLE
import TotalVI, TotalPosterior, TotalTrainer error

### ISSUE THREAD

**Issue by JenniferWUSTL** [YosefLab/scVI#728]
Hi!  I am really looking forward to using TotalVI, but I am having a few issues importing the appropriate models to follow along with the tutorial.  I am running Python 3.7 and scvi 0.6.7 on a MacOS in Jupyter Notebook.

```python
from scvi.models import TOTALVI
from scvi.inference import TotalPosterior, TotalTrainer
```
For these commands, I receive the following errors:
1) `Import Error: cannot import name 'TOTALVI' from 'scvi.models' (~/miniconda3/envs/workshop/lib/python3.7/site-packages/scvi/models/_init_.py)`
2) see photo, and in addition receive: `ImportError: cannot import name 'AnnDatasetfromAnnData' from 'scvi.dataset' ~/miniconda3/envs/workshop/lib/python3.7/site-packages/scvi/dataset/_init_.py)`
![Screen Shot 2020-08-17 at 12 28 27 PM](https://user-images.githubusercontent.com/56699896/90425354-3acce480-e085-11ea-83f0-b59e71b7b55b.png)

Any tips or advice for troubleshooting, would be greatly appreciated!  Thank you!

**Comment by adamgayoso** [comment]
Hi @JenniferWUSTL, could you let us know how you installed scvi? This issue seems somewhat related to #695

**Comment by JenniferWUSTL** [comment]
I installed with: `conda install scvi -c bioconda -c conda-forge`

**Comment by adamgayoso** [comment]
Could you try in a new conda environment first installing PyTorch using their install instructions and then `pip3 install scvi`?

**Comment by JenniferWUSTL** [comment]
Yes, I created the new conda environment and am very pleased to say the errors have been resolved!  Thank you for your very quick help!

**Comment by adamgayoso** [comment]
Thanks for pointing this out. We will test the conda installation out.
