### ISSUE TITLE
number of latent variables

### ISSUE THREAD

**Issue by bsierieb1** [YosefLab/scVI#730]
hi, is there any rule of a thumb how to choose the number of latent variables? i am aware that scvi includes tools for hyperparameter optimization but i wonder if there is a simple (even if not most perfect) solution. thanks!

**Comment by adamgayoso** [comment]
I think a good place to start is hold everything constant and use our estimator for the marginal LL (log p(x)) at different numbers of latent dimensions. This is probably the simplest way to do it but will take a while. 

Using our current API, you can do something like `trainer.test_set.marginal_ll()` after training. I believe this is actually the negative marginal LL so lower should be better.

**Comment by bsierieb1** [comment]
Thanks for the advice @adamgayoso 
I ran into the following error though:
```
trainer.test_set.marginal_ll()
Traceback (most recent call last):

  File "<ipython-input-88-3e632497cd3e>", line 1, in <module>
    trainer.test_set.marginal_ll()

  File "/opt/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)

  File "/opt/anaconda3/lib/python3.7/site-packages/scvi/inference/posterior.py", line 280, in marginal_ll
    ll = compute_marginal_log_likelihood_scvi(self.model, self, n_mc_samples)

  File "/opt/anaconda3/lib/python3.7/site-packages/scvi/models/log_likelihood.py", line 131, in compute_marginal_log_likelihood_scvi
    return -log_lkl / n_samples

ZeroDivisionError: division by zero
```
Am I doing something stupid?
My code:
```
scviDataset = AnnDatasetFromAnnData(adata,batch_label="sample")
    # Train a model
    vae = VAE(
        scviDataset.nb_genes,
        n_batch=scviDataset.n_batches * False,
        n_latent=10,
    )
    trainer = UnsupervisedTrainer(vae, scviDataset, train_size=1.0, use_cuda=False)
    trainer.train(n_epochs=100, lr=1e-3)
    ####    
    trainer.test_set.marginal_ll()

```

**Comment by adamgayoso** [comment]
As you've set `train_size=1.0`, there is no `test_set` you may also do it on the `train_set`.

**Comment by bsierieb1** [comment]
of course, thanks, it works now!
do you think I could use a subset of my data set (say, 10%) to estimate the marginal LL for different n_latent to speed up the process?

**Comment by adamgayoso** [comment]
yes!

**Comment by bsierieb1** [comment]
Amazing, thank you so much!
