### ISSUE TITLE
`AnnDatasetFromAnnData` argument `batch_label` expects a variable type that can be converted to int, not arbitrary string

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scVI#731]
There is a small issue with the documentation of `scvi.dataset.AnnDatasetFromAnnData`: for the `batch_label` argument, it actually expects a variable type that can be converted to int, not arbitrary string. I was getting confused with this when I was trying to give it a column of string that are the names of my different batches/libraries (that look like `L8TX_181211_01_G12`), and was getting the error shown in the screenshot below.

So instead of feeding it the column name with the batch names:
```
gene_dataset = scvi.dataset.AnnDatasetFromAnnData(adata,
                                    batch_label='library_id'
                                  )
```
What I had to do was first was create a new column with the numerical codes for each batch, and then it worked:
```
adata.obs['library_id_codes'] =  adata.obs['library_id'].cat.codes

gene_dataset = scvi.dataset.AnnDatasetFromAnnData(adata,
                                    ctype_label='subclass_label',
                                    batch_label='library_id_codes'
                                  )
```
https://github.com/YosefLab/scVI/blob/54faf80ebadf9294b246b845ac1835278f32a953/scvi/dataset/anndataset.py#L21-L47

![image](https://user-images.githubusercontent.com/12504176/91234729-4619b300-e70a-11ea-82cd-3c94436f0dad.png)

**Comment by adamgayoso** [comment]
Thanks for raising this @Munfred. We might not patch this as we focus on v1.0, which removes these classes and does indeed do allow the batch key to be anything categorical.

**Comment by Munfred** [comment]
Ah great! Are the planned v1.0 changes listed anywhere?

**Comment by adamgayoso** [comment]
Not quite yet. We will figure this out after we merge in our posterior refactor + higher level API PR.

But basically all old code won't work. If you want to get an idea, the [basic tutorial on dev 1.0 ](https://scvi.readthedocs.io/en/dev_v1.0/tutorials/basic_tutorial.html) is from after our dataset changes.

The next step we are working on right now is wrapping the vae module + training into a sklearn-like API, and removing the posterior object as data loader + getting posterior quantities paradigm.

**Comment by Munfred** [comment]
The new all-white documentation theme looks very elegant, I like it and the fonts a lot better than the current theme! 

I see the new logo and the scvi is all lower case instead of scVI. Should I just stick to referring to it as scvi, all lower case, from now on?

**Comment by adamgayoso** [comment]
Thanks! It's the pydata sphinx theme (which is used by pandas), and does look better than the default sphinx rtd theme in my opinion. We are still working on the logo, as well as the naming convention. 

I think what we have for now is that `scvi` lower case is the package name and `scVI` refers specifically to the work done by @romain-lopez. So the convention would be all the methods are like `scANVI`, `totalVI`, `gimVI`, but all reside in the `scvi` package. Though we could decide differently later.
