### ISSUE TITLE
refactoring: remove use_cuda from models

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#75]
It's better if the models (i.e. VAE, VAEC, SVEAC) don't "know" whether they are using cuda or not. In the `__init__` method for these models, we can just load everything on the CPU. Then, call the `.cuda()` method (e.g. `vae.cuda()` right after instantiating the model. It's kind of a detail, but the distinction between the model and what chip it runs on is a helpful one to maintain.

See

https://github.com/YosefLab/scVI/blob/704ce19d80e5728542464e488968c136a241eb6f/scvi/models/vae.py#L46-L48

https://github.com/YosefLab/scVI/blob/704ce19d80e5728542464e488968c136a241eb6f/scvi/models/vaec.py#L40-L43

https://github.com/YosefLab/scVI/blob/704ce19d80e5728542464e488968c136a241eb6f/scvi/models/svaec.py#L47-L50

**Comment by Edouard360** [comment]
Just wondering: so far we used the model `.use_cuda` in the data loader loops.

https://github.com/YosefLab/scVI/blob/704ce19d80e5728542464e488968c136a241eb6f/scvi/metrics/clustering.py#L18-L20

https://github.com/YosefLab/scVI/blob/704ce19d80e5728542464e488968c136a241eb6f/scvi/metrics/classification.py#L39-L41

https://github.com/YosefLab/scVI/blob/704ce19d80e5728542464e488968c136a241eb6f/scvi/metrics/imputation.py#L11-L13

https://github.com/YosefLab/scVI/blob/704ce19d80e5728542464e488968c136a241eb6f/scvi/metrics/log_likelihood.py#L14-L16

I wonder if we should either:

- add an keyword argument `use_cuda` instead to all of these function
- use the `.pin_memory` flag of the dataloaders (which should be set to True in GPU mode)
- smth else ?

**Comment by jeff-regier** [comment]
On the other hand, that all might be overkill. You could just do the `use_cuda` flags if that seems more practical to you.

**Comment by jeff-regier** [comment]
Using the `.pin_memory` flag isn't so good because you can run on cuda without pinning memory. I mean, we never do it, but that wouldn't be clear to someone else reading the code.

Yeah, I propose having a `use_cuda` flag in the argument lists for now.

I'd like to revisit the `InferenceTask` idea ultimately because I think it has a number of benefits, but I think it's overkill for this github issue.
