### ISSUE TITLE
refactoring: VAEC and SVAEC as subclasses of VAE

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#76]
There's a lot of duplicated code in the VAE, VAEC, and SVAEC classes. To get rid of it, lets make VAEC and SVAEC subclasses of VAE. In addition to avoiding duplicated code (which is hard to maintain), it's nice conceptually to express our semi-supervised models as specializations or our unsupervised scVI model.

Also, I wonder about whether SVAEC could inherit from VAEC, or whether even we need both SVAEC and VAEC.

**Comment by Edouard360** [comment]
For sure, we can at least factorize `__init__`, `sample_from_posterior_z`, `sample_from_posterior_l`, `get_sample_scale`,  `get_sample_rate` based on the VAE class. I can take care of that. However the `forward` methods seems difficult to inherit, so there will be full overriding for VAEC and SVAEC I imagine. I think SVAEC can't inherit anything VAEC: for the `__init__` their Classifier has different `n_input`, `n_ouput`, and for the `forward` the only edges in common are already the ones shared with `VAE`.

**Comment by Edouard360** [comment]
431d066: started doing it.
Not sure, however, about how to factorize forward without creating intermediary methods with long arguments list and long signatures.

**Comment by jeff-regier** [comment]
You're right -- we don't want tiny functions with long argument lists. Maybe fine to have some duplicated code in forward methods then.
