### ISSUE TITLE
refactoring: combine training method

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#77]
There's a lot of code duplicated across our four methods for training models: `train`, `train_semi_supervised_jointly`, `train_semi_supervised_alternately`, and `train_classifier`. How about combining all these methods into one method, `train`, and passing it additional arguments (e.g., boolean flags) to control how it behaves?

**Comment by Edouard360** [comment]
Would creating a `Train` class also work ? Where we would inherit a loop method, ect... ? 

I feel like a single function with flags would be less readable.

**Comment by jeff-regier** [comment]
Yes, that might work. Maybe call it `Trainer`, with `train` as a method.

**Comment by Edouard360** [comment]
I went from ~180 to ~100 lines in branch [trainer](/YosefLab/scVI/tree/trainer), which includes modifications from branch [refactoring](/YosefLab/scVI/tree/refactoring) therefore aiming at solving also #76 and #75.

Do you agree with the `Trainer` class design ? (which might be refined before the pull request)

**Comment by jeff-regier** [comment]
Yes, looks like a nice improvement.
