### ISSUE TITLE
additional datasets

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#78]
@imyiningliu  -- I think Maxime, Eddie, and Chenling are all working with datasets now that aren't yet "wrapped" by scVI.  It'd be great if you could talk with all three of them to find out what datasets they're using, and add one class (that inherits from `GeneExpressionDataset`) for each dataset they plan to keep using. They may already have some code, which they haven't committed yet, that you can start with.  We'd also want some documentation for each dataset, and a unit test if the new dataset requires a non-trivial amount of code.

These new datasets may have some characteristics that are different from the dataset we've seen so far.
-- Maxime's smFISH datasets have position information. I think he had some ideas for how to modify `GeneExpressionDataset` to include that information.
-- Eddie's pbmc donor data may already be accessible through the Dataset10x class.
-- Chenling's data from the simulator isn't available on at any public url yet, and maybe it's too early to make it public. But if not, we could share it through our scVI-dev repo.

Also, I'm interested in getting access through scVI to the dataset mentioned in this paper: https://www.nature.com/articles/nmeth.4636

**Comment by Edouard360** [comment]
With regard to my dataset, the raw counts are indeed already accessible through the `Dataset10X` class:

I could theoretically simply run something like:

```
cd4_t_helper = Dataset10X("cd4_t_helper", dense=False, new_n_genes=None)
regulatory_t = Dataset10X("regulatory_t", dense=False, new_n_genes=None)
naive_t = Dataset10X("naive_t", dense=False, new_n_genes=None)
memory_t = Dataset10X("memory_t", dense=False, new_n_genes=None)
cytotoxic_t = Dataset10X("cytotoxic_t", dense=False, new_n_genes=None)
naive_cytotoxic = Dataset10X("naive_cytotoxic", dense=False, new_n_genes=None)

fresh_68k_pbmc_donor_a = Dataset10X("fresh_68k_pbmc_donor_a", dense=False, new_n_genes=None)

cite_seq_pbmc = CiteSeqDataset("pbmc")

t_cells = GeneExpressionDataset.concat_datasets(cd4_t_helper,regulatory_t,naive_t,memory_t,cytotoxic_t,naive_cytotoxic)
all_concatenated_pbmcs = GeneExpressionDataset.concat_datasets(t_cells, fresh_68k_pbmc_donor_a, cite_seq_pbmc, shared_batches=False)
```

However, initially I would work with the `.rds` data coming from [this repo](https://github.com/10XGenomics/single-cell-3prime-paper/tree/master/pbmc68k_analysis), as well as its preprocessing scripts, which gave me additional information:

- the `gene_symbols` without which I can't merge the datasets with citeSeq (10X Datasets only use the ENSEMBL version for the gene names, and I didn't find any mapping yet).

- the `predicted labels` from the original ["Massively Parallel ..."](https://www.nature.com/articles/ncomms14049) paper, which one has to compute for himself (they don't give it in an output file).

**Comment by jeff-regier** [comment]
@imyiningliu  @Edouard360  Are there additional datasets we plan to keep using, that aren't wrapped by scVI, beyond what Yining added in #97 ? If not, let's close this issue.

**Comment by Edouard360** [comment]
Let me add scmap datasets, and I'll be good
