### ISSUE TITLE
imputation based on multiple samples

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#80]
Our imputation results are based on just one sample from the variational distribution currently:

https://github.com/YosefLab/scVI/blob/704ce19d80e5728542464e488968c136a241eb6f/scvi/metrics/imputation.py#L24

That makes imputation not much of a metric for assessing changes to our model --- I'm surprised it works as well as it does. We should be sure to fix it before relying on imputation scores to guide any modeling decisions.

**Comment by jeff-regier** [comment]
This issue might be why we get outperformed by zinb-wave (Figure 11 from the paper):

![figure-3_non_unif](https://user-images.githubusercontent.com/8953355/43023760-cf8251f2-8c20-11e8-8d76-ae81ad64a7ab.png)

I also think the wake-sleep training we discussed, @Edouard360 , could lead to a big improvement in this metric.

**Comment by Edouard360** [comment]
Yep will do it some time today !
