### ISSUE TITLE
tqdm causes headaches with Jupyter Lab

### ISSUE THREAD

**Issue by jamestwebber** [YosefLab/scVI#81]
Impressed with the progress here! I'm trying this out on our data ([the "Tabula Muris" dataset](http://tabula-muris.ds.czbiohub.org/)) but I've been using JupyterLab and I ran into some issues with your notebooks (which are super helpful by the way).

Looking into it, it appears to be an issue with interactive output and JupyterLab. Given that it's a work-in-progress it's probably not worth trying to maintain compatibility (I'm about to file a bug with them about this), but it would be nice if I could just disable the progress bar, which would prevent the issue from coming up.

**Comment by jeff-regier** [comment]
Hi James, Thanks for trying out scVI, and for bringing the `tqdm_notebook`/JupyterLab incompatibility to our attention. We don't really need that `tqdm_notebook` Jupyter widget, it turns out. I'll get rid of it in PR #82 . Please let me know whether that fixes the problem!
