### ISSUE TITLE
sharing datasets for development

### ISSUE THREAD

**Issue by Edouard360** [YosefLab/scVI#96]
@chenlingantelope has an interesting dataset in which the batch mixing problem isn't solved. It might be interesting for @maxime1310 and I to investigate new harmonizing methods on that instance.

I had a piece of code I wondered if I could include it a a GeneExpressionDataset method:

```python
    def export(self, filename):
        col_attrs = {"BatchID": self.batch_indices, "ClusterID": self.labels}
        row_attrs = dict()
        file_attrs = dict()
        if hasattr(self, "gene_names"):
            row_attrs["Gene"] = self.gene_names
        if hasattr(self, "cell_types"):
            file_attrs["CellTypes"] = self.cell_types
        loompy.create("data/" + filename, self.X.T, row_attrs, col_attrs, file_attrs=file_attrs)
```

That might be convenient for exchanging datasets in the `.loom` format.

**Comment by Edouard360** [comment]
This might especially be useful **as long as there is preprocessing** to the "harmonization" task (and not simply the concatenation of already existing datasets). For instance for my latest PBMCs experiments I labelled cell types from cite seq according to epitopes level, and in particular the CD4 label I extracted had a much lower level of granularity that on purified populations where subcell types were also identified. So I merge the CD4 labels on the purified samples, and only kept the cell types appearing in both datasets, which gives me a convenient subsampled version of a dataset with batch and labels preannotation on which we know harmonization should work.

**Comment by jeff-regier** [comment]
I don't think anything in `GeneExpressionDataset` should be specific to loom. What about just pickling the dataset object and sharing it with each other that way?

**Comment by jeff-regier** [comment]
If Chenling has a good dataset for testing, could we post it (in loom format, or in whatever format) at https://github.com/YosefLab/scVI-data

That's the kind of thing @imyiningliu might work on for issue #78

**Comment by jeff-regier** [comment]
Let's use `pickle` serialization for now.
